#==============================================================================
# 990_NPT — New Pokémon Tool
# File: 002_SplitNames.rb
# Purpose: Register fusion-name syllables for every custom Pokémon.
#
# WHY THIS IS NEEDED
# ──────────────────
# When a fusion is created, FusedSpecies#calculate_name() looks up
# GameData::SPLIT_NAMES[head_nat_dex] and GameData::SPLIT_NAMES[body_nat_dex]
# to build a combined name (e.g. "Pika" + "saur" → "Pikasaur").
#
# The SPLIT_NAMES array currently goes up to index ~907 (highest national dex
# remapped from a game ID).  IDs 502+ have no entry there, so without this
# file the fusion name step would rescue silently and return nil — resulting in
# a nameless fusion.
#
# HOW IT WORKS
# ────────────
# 1. We tell NAT_DEX_MAPPING to redirect each new species' id_number to a
#    fresh index (NPT::SPLIT_NAMES_BASE_INDEX + offset = 950, 951, 952 …).
# 2. We write the [prefix, suffix] pair into SPLIT_NAMES at that index.
#
# This keeps new entries away from the existing 1–907 range so we never
# accidentally shadow a live game entry.
#
# HOW TO ADD SPLIT-NAMES FOR A NEW POKÉMON
# ─────────────────────────────────────────
# Call NPT.register_split_name(id_number, prefix, suffix)
# where id_number matches what you used in 001_Registration.rb.
#
# Naming tips
# ───────────
# • prefix: the opening syllable(s) of a fusion where your Pokémon is the HEAD
#           (contributes its front half to the fused name).
# • suffix: the closing syllable(s) of a fusion where your Pokémon is the BODY
#           (contributes its back half to the fused name).
# • If prefix ends with the same letter that suffix begins with, the engine
#   removes the duplicate automatically.  You don't need to pre-trim.
# • Keep each part 2–6 characters for readability (e.g. "Exa" / "mon").
#==============================================================================

module NPT
  # Internal offset counter — do not edit directly.
  @split_name_offset = 0

  # Register fusion-name syllables for a custom Pokémon.
  #
  # @param id_number [Integer]  The species id_number from 001_Registration.rb
  # @param prefix    [String]   Head syllable(s) used when this Pokémon is head
  # @param suffix    [String]   Body syllable(s) used when this Pokémon is body
  def self.register_split_name(id_number, prefix, suffix)
    slot = NPT::SPLIT_NAMES_BASE_INDEX + @split_name_offset
    GameData::NAT_DEX_MAPPING[id_number] = slot
    GameData::SPLIT_NAMES[slot]          = [prefix, suffix]
    @split_name_offset += 1
    echoln "[990_NPT] Split name registered: id=#{id_number} → [\"#{prefix}\", \"#{suffix}\"] at SPLIT_NAMES[#{slot}]"
  end
end

# ── Split names for registered custom species ──────────────────────────────────
# One call per species, in the same order as 001_Registration.rb.
#
# NPT.register_split_name(id_number, "Prefix", "suffix")

# Auto-generated split names — regenerated by generate_npt_registrations.rb
# Syllables are approximate; adjust any that produce ugly fusion names.

# Auto-generated split names — paste into 002_SplitNames.rb
# Syllables are approximate; fix any that produce ugly fusion names.

NPT.register_split_name(502, "Pooc", "hyena")   # Poochyena
NPT.register_split_name(503, "Migh", "tyena")   # Mightyena
NPT.register_split_name(504, "Zigz", "agoon")   # Zigzagoon
NPT.register_split_name(505, "Lino", "one")   # Linoone
NPT.register_split_name(506, "Wurm", "ple")   # Wurmple
NPT.register_split_name(507, "Silc", "oon")   # Silcoon
NPT.register_split_name(508, "Beau", "tifly")   # Beautifly
NPT.register_split_name(509, "Casc", "oon")   # Cascoon
NPT.register_split_name(510, "Dus", "tox")   # Dustox
NPT.register_split_name(511, "See", "dot")   # Seedot
NPT.register_split_name(512, "Nuzl", "eaf")   # Nuzleaf
NPT.register_split_name(513, "Shif", "try")   # Shiftry
NPT.register_split_name(514, "Tail", "low")   # Taillow
NPT.register_split_name(515, "Swel", "low")   # Swellow
NPT.register_split_name(516, "Wing", "ull")   # Wingull
NPT.register_split_name(517, "Peli", "pper")   # Pelipper
NPT.register_split_name(518, "Surs", "kit")   # Surskit
NPT.register_split_name(519, "Masqu", "erain")   # Masquerain
NPT.register_split_name(520, "Whis", "mur")   # Whismur
NPT.register_split_name(521, "Loud", "red")   # Loudred
NPT.register_split_name(522, "Expl", "oud")   # Exploud
NPT.register_split_name(523, "Maku", "hita")   # Makuhita
NPT.register_split_name(524, "Hari", "yama")   # Hariyama
NPT.register_split_name(525, "Ski", "tty")   # Skitty
NPT.register_split_name(526, "Delc", "atty")   # Delcatty
NPT.register_split_name(527, "Medi", "tite")   # Meditite
NPT.register_split_name(528, "Medi", "cham")   # Medicham
NPT.register_split_name(529, "Elec", "trike")   # Electrike
NPT.register_split_name(530, "Mane", "ctric")   # Manectric
NPT.register_split_name(531, "Plu", "sle")   # Plusle
NPT.register_split_name(532, "Min", "un")   # Minun
NPT.register_split_name(533, "Volb", "eat")   # Volbeat
NPT.register_split_name(534, "Illu", "mise")   # Illumise
NPT.register_split_name(535, "Gul", "pin")   # Gulpin
NPT.register_split_name(536, "Swa", "lot")   # Swalot
NPT.register_split_name(537, "Num", "el")   # Numel
NPT.register_split_name(538, "Came", "rupt")   # Camerupt
NPT.register_split_name(539, "Spo", "ink")   # Spoink
NPT.register_split_name(540, "Grum", "pig")   # Grumpig
NPT.register_split_name(541, "Spi", "nda")   # Spinda
NPT.register_split_name(542, "Zang", "oose")   # Zangoose
NPT.register_split_name(543, "Sevi", "per")   # Seviper
NPT.register_split_name(544, "Luna", "tone")   # Lunatone
NPT.register_split_name(545, "Solr", "ock")   # Solrock
NPT.register_split_name(546, "Barb", "oach")   # Barboach
NPT.register_split_name(547, "Whis", "cash")   # Whiscash
NPT.register_split_name(548, "Corp", "hish")   # Corphish
NPT.register_split_name(549, "Craw", "daunt")   # Crawdaunt
NPT.register_split_name(550, "Bal", "toy")   # Baltoy
NPT.register_split_name(551, "Clay", "dol")   # Claydol
NPT.register_split_name(552, "Cast", "form")   # Castform
NPT.register_split_name(553, "Trop", "ius")   # Tropius
NPT.register_split_name(554, "Chim", "echo")   # Chimecho
NPT.register_split_name(555, "Sph", "eal")   # Spheal
NPT.register_split_name(556, "Sea", "leo")   # Sealeo
NPT.register_split_name(557, "Walr", "ein")   # Walrein
NPT.register_split_name(558, "Clam", "perl")   # Clamperl
NPT.register_split_name(559, "Hunt", "ail")   # Huntail
NPT.register_split_name(560, "Gore", "byss")   # Gorebyss
NPT.register_split_name(561, "Reli", "canth")   # Relicanth
NPT.register_split_name(562, "Sta", "rly")   # Starly
NPT.register_split_name(563, "Star", "avia")   # Staravia
NPT.register_split_name(564, "Star", "aptor")   # Staraptor
NPT.register_split_name(565, "Kric", "ketot")   # Kricketot
NPT.register_split_name(566, "Krick", "etune")   # Kricketune
NPT.register_split_name(567, "Bur", "my")   # Burmy
NPT.register_split_name(568, "Worm", "adam")   # Wormadam
NPT.register_split_name(569, "Mot", "him")   # Mothim
NPT.register_split_name(570, "Com", "bee")   # Combee
NPT.register_split_name(571, "Vesp", "iquen")   # Vespiquen
NPT.register_split_name(572, "Pach", "irisu")   # Pachirisu
NPT.register_split_name(573, "Bui", "zel")   # Buizel
NPT.register_split_name(574, "Floa", "tzel")   # Floatzel
NPT.register_split_name(575, "Cher", "ubi")   # Cherubi
NPT.register_split_name(576, "Cher", "rim")   # Cherrim
NPT.register_split_name(577, "Shel", "los")   # Shellos
NPT.register_split_name(578, "Gast", "rodon")   # Gastrodon
NPT.register_split_name(579, "Glam", "eow")   # Glameow
NPT.register_split_name(580, "Puru", "gly")   # Purugly
NPT.register_split_name(581, "Chin", "gling")   # Chingling
NPT.register_split_name(582, "Stu", "nky")   # Stunky
NPT.register_split_name(583, "Skun", "tank")   # Skuntank
NPT.register_split_name(584, "Bron", "zor")   # Bronzor
NPT.register_split_name(585, "Bron", "zong")   # Bronzong
NPT.register_split_name(586, "Cha", "tot")   # Chatot
NPT.register_split_name(587, "Hippo", "potas")   # Hippopotas
NPT.register_split_name(588, "Hipp", "owdon")   # Hippowdon
NPT.register_split_name(589, "Skor", "upi")   # Skorupi
NPT.register_split_name(590, "Drap", "ion")   # Drapion
NPT.register_split_name(591, "Croa", "gunk")   # Croagunk
NPT.register_split_name(592, "Toxi", "croak")   # Toxicroak
NPT.register_split_name(593, "Carn", "ivine")   # Carnivine
NPT.register_split_name(594, "Finn", "eon")   # Finneon
NPT.register_split_name(595, "Lumi", "neon")   # Lumineon
NPT.register_split_name(596, "Sno", "ver")   # Snover
NPT.register_split_name(597, "Abom", "asnow")   # Abomasnow
NPT.register_split_name(598, "Ux", "ie")   # Uxie
NPT.register_split_name(599, "Mesp", "rit")   # Mesprit
NPT.register_split_name(600, "Aze", "lf")   # Azelf
NPT.register_split_name(601, "Heat", "ran")   # Heatran
NPT.register_split_name(602, "Phi", "one")   # Phione
NPT.register_split_name(603, "Mana", "phy")   # Manaphy
NPT.register_split_name(604, "Shay", "min")   # Shaymin
NPT.register_split_name(605, "Vict", "ini")   # Victini
NPT.register_split_name(606, "Sni", "vy")   # Snivy
NPT.register_split_name(607, "Serv", "ine")   # Servine
NPT.register_split_name(608, "Serp", "erior")   # Serperior
NPT.register_split_name(609, "Tep", "ig")   # Tepig
NPT.register_split_name(610, "Pign", "ite")   # Pignite
NPT.register_split_name(611, "Emb", "oar")   # Emboar
NPT.register_split_name(612, "Osha", "wott")   # Oshawott
NPT.register_split_name(613, "Dew", "ott")   # Dewott
NPT.register_split_name(614, "Samu", "rott")   # Samurott
NPT.register_split_name(615, "Pat", "rat")   # Patrat
NPT.register_split_name(616, "Watc", "hog")   # Watchog
NPT.register_split_name(617, "Lill", "ipup")   # Lillipup
NPT.register_split_name(618, "Herd", "ier")   # Herdier
NPT.register_split_name(619, "Stou", "tland")   # Stoutland
NPT.register_split_name(620, "Purr", "loin")   # Purrloin
NPT.register_split_name(621, "Liep", "ard")   # Liepard
NPT.register_split_name(622, "Pans", "age")   # Pansage
NPT.register_split_name(623, "Simi", "sage")   # Simisage
NPT.register_split_name(624, "Pans", "ear")   # Pansear
NPT.register_split_name(625, "Simi", "sear")   # Simisear
NPT.register_split_name(626, "Panp", "our")   # Panpour
NPT.register_split_name(627, "Simi", "pour")   # Simipour
NPT.register_split_name(628, "Mun", "na")   # Munna
NPT.register_split_name(629, "Mush", "arna")   # Musharna
NPT.register_split_name(630, "Pid", "ove")   # Pidove
NPT.register_split_name(631, "Tran", "quill")   # Tranquill
NPT.register_split_name(632, "Unfe", "zant")   # Unfezant
NPT.register_split_name(633, "Blit", "zle")   # Blitzle
NPT.register_split_name(634, "Zebs", "trika")   # Zebstrika
NPT.register_split_name(635, "Rogge", "nrola")   # Roggenrola
NPT.register_split_name(636, "Bold", "ore")   # Boldore
NPT.register_split_name(637, "Giga", "lith")   # Gigalith
NPT.register_split_name(638, "Woo", "bat")   # Woobat
NPT.register_split_name(639, "Swoo", "bat")   # Swoobat
NPT.register_split_name(640, "Dril", "bur")   # Drilbur
NPT.register_split_name(641, "Exca", "drill")   # Excadrill
NPT.register_split_name(642, "Aud", "ino")   # Audino
NPT.register_split_name(643, "Timb", "urr")   # Timburr
NPT.register_split_name(644, "Gurd", "urr")   # Gurdurr
NPT.register_split_name(645, "Conke", "ldurr")   # Conkeldurr
NPT.register_split_name(646, "Tymp", "ole")   # Tympole
NPT.register_split_name(647, "Palp", "itoad")   # Palpitoad
NPT.register_split_name(648, "Seism", "itoad")   # Seismitoad
NPT.register_split_name(649, "Thr", "oh")   # Throh
NPT.register_split_name(650, "Sa", "wk")   # Sawk
NPT.register_split_name(651, "Sewa", "ddle")   # Sewaddle
NPT.register_split_name(652, "Swad", "loon")   # Swadloon
NPT.register_split_name(653, "Leav", "anny")   # Leavanny
NPT.register_split_name(654, "Peti", "lil")   # Petilil
NPT.register_split_name(655, "Lill", "igant")   # Lilligant
NPT.register_split_name(656, "Basc", "ulin")   # Basculin
NPT.register_split_name(657, "Daru", "maka")   # Darumaka
NPT.register_split_name(658, "Darma", "nitan")   # Darmanitan
NPT.register_split_name(659, "Mara", "ctus")   # Maractus
NPT.register_split_name(660, "Dweb", "ble")   # Dwebble
NPT.register_split_name(661, "Crus", "tle")   # Crustle
NPT.register_split_name(662, "Sigi", "lyph")   # Sigilyph
NPT.register_split_name(663, "Tirt", "ouga")   # Tirtouga
NPT.register_split_name(664, "Carra", "costa")   # Carracosta
NPT.register_split_name(665, "Arc", "hen")   # Archen
NPT.register_split_name(666, "Arch", "eops")   # Archeops
NPT.register_split_name(667, "Minc", "cino")   # Minccino
NPT.register_split_name(668, "Cinc", "cino")   # Cinccino
NPT.register_split_name(669, "Goth", "ita")   # Gothita
NPT.register_split_name(670, "Goth", "orita")   # Gothorita
NPT.register_split_name(671, "Gothi", "telle")   # Gothitelle
NPT.register_split_name(672, "Duck", "lett")   # Ducklett
NPT.register_split_name(673, "Swa", "nna")   # Swanna
NPT.register_split_name(674, "Vani", "llite")   # Vanillite
NPT.register_split_name(675, "Vani", "llish")   # Vanillish
NPT.register_split_name(676, "Vani", "lluxe")   # Vanilluxe
NPT.register_split_name(677, "Deer", "ling")   # Deerling
NPT.register_split_name(678, "Saws", "buck")   # Sawsbuck
NPT.register_split_name(679, "Emo", "lga")   # Emolga
NPT.register_split_name(680, "Karra", "blast")   # Karrablast
NPT.register_split_name(681, "Escav", "alier")   # Escavalier
NPT.register_split_name(682, "Foon", "gus")   # Foongus
NPT.register_split_name(683, "Amoo", "nguss")   # Amoonguss
NPT.register_split_name(684, "Fril", "lish")   # Frillish
NPT.register_split_name(685, "Jell", "icent")   # Jellicent
NPT.register_split_name(686, "Alom", "omola")   # Alomomola
NPT.register_split_name(687, "Tyn", "amo")   # Tynamo
NPT.register_split_name(688, "Eele", "ktrik")   # Eelektrik
NPT.register_split_name(689, "Eelek", "tross")   # Eelektross
NPT.register_split_name(690, "Elg", "yem")   # Elgyem
NPT.register_split_name(691, "Behe", "eyem")   # Beheeyem
NPT.register_split_name(692, "Cubc", "hoo")   # Cubchoo
NPT.register_split_name(693, "Bear", "tic")   # Beartic
NPT.register_split_name(694, "Cryo", "gonal")   # Cryogonal
NPT.register_split_name(695, "Shel", "met")   # Shelmet
NPT.register_split_name(696, "Acce", "lgor")   # Accelgor
NPT.register_split_name(697, "Mien", "foo")   # Mienfoo
NPT.register_split_name(698, "Mien", "shao")   # Mienshao
NPT.register_split_name(699, "Drud", "digon")   # Druddigon
NPT.register_split_name(700, "Bouff", "alant")   # Bouffalant
NPT.register_split_name(701, "Ruff", "let")   # Rufflet
NPT.register_split_name(702, "Brav", "iary")   # Braviary
NPT.register_split_name(703, "Vull", "aby")   # Vullaby
NPT.register_split_name(704, "Mand", "ibuzz")   # Mandibuzz
NPT.register_split_name(705, "Heat", "mor")   # Heatmor
NPT.register_split_name(706, "Dur", "ant")   # Durant
NPT.register_split_name(707, "Coba", "lion")   # Cobalion
NPT.register_split_name(708, "Terr", "akion")   # Terrakion
NPT.register_split_name(709, "Viri", "zion")   # Virizion
NPT.register_split_name(710, "Torn", "adus")   # Tornadus
NPT.register_split_name(711, "Thun", "durus")   # Thundurus
NPT.register_split_name(712, "Land", "orus")   # Landorus
NPT.register_split_name(713, "Kel", "deo")   # Keldeo
NPT.register_split_name(714, "Bunn", "elby")   # Bunnelby
NPT.register_split_name(715, "Digg", "ersby")   # Diggersby
NPT.register_split_name(716, "Scatt", "erbug")   # Scatterbug
NPT.register_split_name(717, "Spe", "wpa")   # Spewpa
NPT.register_split_name(718, "Vivi", "llon")   # Vivillon
NPT.register_split_name(719, "Lit", "leo")   # Litleo
NPT.register_split_name(720, "Pyr", "oar")   # Pyroar
NPT.register_split_name(721, "Fla", "bb")   # Flabébé
NPT.register_split_name(722, "Floe", "tte")   # Floette
NPT.register_split_name(723, "Flor", "ges")   # Florges
NPT.register_split_name(724, "Ski", "ddo")   # Skiddo
NPT.register_split_name(725, "Gog", "oat")   # Gogoat
NPT.register_split_name(726, "Panc", "ham")   # Pancham
NPT.register_split_name(727, "Pang", "oro")   # Pangoro
NPT.register_split_name(728, "Furf", "rou")   # Furfrou
NPT.register_split_name(729, "Esp", "urr")   # Espurr
NPT.register_split_name(730, "Meow", "stic")   # Meowstic
NPT.register_split_name(731, "Spri", "tzee")   # Spritzee
NPT.register_split_name(732, "Aroma", "tisse")   # Aromatisse
NPT.register_split_name(733, "Ink", "ay")   # Inkay
NPT.register_split_name(734, "Mala", "mar")   # Malamar
NPT.register_split_name(735, "Bina", "cle")   # Binacle
NPT.register_split_name(736, "Barba", "racle")   # Barbaracle
NPT.register_split_name(737, "Skr", "elp")   # Skrelp
NPT.register_split_name(738, "Drag", "alge")   # Dragalge
NPT.register_split_name(739, "Clau", "ncher")   # Clauncher
NPT.register_split_name(740, "Claw", "itzer")   # Clawitzer
NPT.register_split_name(741, "Helio", "ptile")   # Helioptile
NPT.register_split_name(742, "Heli", "olisk")   # Heliolisk
NPT.register_split_name(743, "Dede", "nne")   # Dedenne
NPT.register_split_name(744, "Berg", "mite")   # Bergmite
NPT.register_split_name(745, "Aval", "ugg")   # Avalugg
NPT.register_split_name(746, "Xern", "eas")   # Xerneas
NPT.register_split_name(747, "Yvel", "tal")   # Yveltal
NPT.register_split_name(748, "Zyga", "rde")   # Zygarde
NPT.register_split_name(749, "Hoo", "pa")   # Hoopa
NPT.register_split_name(750, "Volc", "anion")   # Volcanion
NPT.register_split_name(751, "Row", "let")   # Rowlet
NPT.register_split_name(752, "Dart", "rix")   # Dartrix
NPT.register_split_name(753, "Deci", "dueye")   # Decidueye
NPT.register_split_name(754, "Lit", "ten")   # Litten
NPT.register_split_name(755, "Torr", "acat")   # Torracat
NPT.register_split_name(756, "Incin", "eroar")   # Incineroar
NPT.register_split_name(757, "Popp", "lio")   # Popplio
NPT.register_split_name(758, "Brio", "nne")   # Brionne
NPT.register_split_name(759, "Prim", "arina")   # Primarina
NPT.register_split_name(760, "Piki", "pek")   # Pikipek
NPT.register_split_name(761, "Trum", "beak")   # Trumbeak
NPT.register_split_name(762, "Touc", "annon")   # Toucannon
NPT.register_split_name(763, "Yung", "oos")   # Yungoos
NPT.register_split_name(764, "Gums", "hoos")   # Gumshoos
NPT.register_split_name(765, "Grub", "bin")   # Grubbin
NPT.register_split_name(766, "Char", "jabug")   # Charjabug
NPT.register_split_name(767, "Vika", "volt")   # Vikavolt
NPT.register_split_name(768, "Crabr", "awler")   # Crabrawler
NPT.register_split_name(769, "Crabo", "able")   # Crabominable
NPT.register_split_name(770, "Cuti", "efly")   # Cutiefly
NPT.register_split_name(771, "Ribo", "mbee")   # Ribombee
NPT.register_split_name(772, "Wishi", "washi")   # Wishiwashi
NPT.register_split_name(773, "Mudb", "ray")   # Mudbray
NPT.register_split_name(774, "Muds", "dale")   # Mudsdale
NPT.register_split_name(775, "Dewp", "ider")   # Dewpider
NPT.register_split_name(776, "Araq", "uanid")   # Araquanid
NPT.register_split_name(777, "More", "lull")   # Morelull
NPT.register_split_name(778, "Shii", "notic")   # Shiinotic
NPT.register_split_name(779, "Sala", "ndit")   # Salandit
NPT.register_split_name(780, "Sala", "zzle")   # Salazzle
NPT.register_split_name(781, "Boun", "sweet")   # Bounsweet
NPT.register_split_name(782, "Stee", "nee")   # Steenee
NPT.register_split_name(783, "Tsar", "eena")   # Tsareena
NPT.register_split_name(784, "Com", "fey")   # Comfey
NPT.register_split_name(785, "Oran", "guru")   # Oranguru
NPT.register_split_name(786, "Pass", "imian")   # Passimian
NPT.register_split_name(787, "Type", "null")   # Type: Null
NPT.register_split_name(788, "Silv", "ally")   # Silvally
NPT.register_split_name(789, "Kom", "ala")   # Komala
NPT.register_split_name(790, "Turto", "nator")   # Turtonator
NPT.register_split_name(791, "Toged", "emaru")   # Togedemaru
NPT.register_split_name(792, "Dra", "mpa")   # Drampa
NPT.register_split_name(793, "Tapu", "koko")   # Tapu Koko
NPT.register_split_name(794, "Tapu", "lele")   # Tapu Lele
NPT.register_split_name(795, "Tapu", "bulu")   # Tapu Bulu
NPT.register_split_name(796, "Tapu", "fini")   # Tapu Fini
NPT.register_split_name(797, "Cos", "mog")   # Cosmog
NPT.register_split_name(798, "Cosm", "oem")   # Cosmoem
NPT.register_split_name(799, "Solg", "aleo")   # Solgaleo
NPT.register_split_name(800, "Lun", "ala")   # Lunala
NPT.register_split_name(801, "Nihi", "lego")   # Nihilego
NPT.register_split_name(802, "Buzz", "wole")   # Buzzwole
NPT.register_split_name(803, "Pher", "omosa")   # Pheromosa
NPT.register_split_name(804, "Xurk", "itree")   # Xurkitree
NPT.register_split_name(805, "Celes", "teela")   # Celesteela
NPT.register_split_name(806, "Kart", "ana")   # Kartana
NPT.register_split_name(807, "Guzz", "lord")   # Guzzlord
NPT.register_split_name(808, "Mage", "arna")   # Magearna
NPT.register_split_name(809, "Mars", "hadow")   # Marshadow
NPT.register_split_name(810, "Poip", "ole")   # Poipole
NPT.register_split_name(811, "Naga", "nadel")   # Naganadel
NPT.register_split_name(812, "Stak", "ataka")   # Stakataka
NPT.register_split_name(813, "Blace", "alon")   # Blacephalon
NPT.register_split_name(814, "Zera", "ora")   # Zeraora
NPT.register_split_name(815, "Mel", "tan")   # Meltan
NPT.register_split_name(816, "Melm", "etal")   # Melmetal
NPT.register_split_name(817, "Groo", "key")   # Grookey
NPT.register_split_name(818, "Thwa", "ckey")   # Thwackey
NPT.register_split_name(819, "Rill", "aboom")   # Rillaboom
NPT.register_split_name(820, "Scor", "bunny")   # Scorbunny
NPT.register_split_name(821, "Rab", "oot")   # Raboot
NPT.register_split_name(822, "Cind", "erace")   # Cinderace
NPT.register_split_name(823, "Sob", "ble")   # Sobble
NPT.register_split_name(824, "Driz", "zile")   # Drizzile
NPT.register_split_name(825, "Inte", "leon")   # Inteleon
NPT.register_split_name(826, "Skwo", "vet")   # Skwovet
NPT.register_split_name(827, "Gree", "dent")   # Greedent
NPT.register_split_name(828, "Rook", "idee")   # Rookidee
NPT.register_split_name(829, "Corvi", "uire")   # Corvisquire
NPT.register_split_name(830, "Corvi", "ight")   # Corviknight
NPT.register_split_name(831, "Blip", "bug")   # Blipbug
NPT.register_split_name(832, "Dott", "ler")   # Dottler
NPT.register_split_name(833, "Orbe", "etle")   # Orbeetle
NPT.register_split_name(834, "Nic", "kit")   # Nickit
NPT.register_split_name(835, "Thie", "vul")   # Thievul
NPT.register_split_name(836, "Gossi", "fleur")   # Gossifleur
NPT.register_split_name(837, "Elde", "goss")   # Eldegoss
NPT.register_split_name(838, "Woo", "loo")   # Wooloo
NPT.register_split_name(839, "Dubw", "ool")   # Dubwool
NPT.register_split_name(840, "Chew", "tle")   # Chewtle
NPT.register_split_name(841, "Dred", "naw")   # Drednaw
NPT.register_split_name(842, "Yam", "per")   # Yamper
NPT.register_split_name(843, "Bolt", "und")   # Boltund
NPT.register_split_name(844, "Roly", "coly")   # Rolycoly
NPT.register_split_name(845, "Car", "kol")   # Carkol
NPT.register_split_name(846, "Coal", "ossal")   # Coalossal
NPT.register_split_name(847, "App", "lin")   # Applin
NPT.register_split_name(848, "Flap", "ple")   # Flapple
NPT.register_split_name(849, "Appl", "etun")   # Appletun
NPT.register_split_name(850, "Sili", "cobra")   # Silicobra
NPT.register_split_name(851, "Sanda", "conda")   # Sandaconda
NPT.register_split_name(852, "Cram", "orant")   # Cramorant
NPT.register_split_name(853, "Arro", "kuda")   # Arrokuda
NPT.register_split_name(854, "Barra", "ewda")   # Barraskewda
NPT.register_split_name(855, "Tox", "el")   # Toxel
NPT.register_split_name(856, "Toxtr", "icity")   # Toxtricity
NPT.register_split_name(857, "Sizzl", "ipede")   # Sizzlipede
NPT.register_split_name(858, "Centi", "orch")   # Centiskorch
NPT.register_split_name(859, "Clob", "bopus")   # Clobbopus
NPT.register_split_name(860, "Grap", "ploct")   # Grapploct
NPT.register_split_name(861, "Sini", "stea")   # Sinistea
NPT.register_split_name(862, "Polte", "eist")   # Polteageist
NPT.register_split_name(863, "Hate", "nna")   # Hatenna
NPT.register_split_name(864, "Hatt", "rem")   # Hattrem
NPT.register_split_name(865, "Hatt", "erene")   # Hatterene
NPT.register_split_name(866, "Impi", "dimp")   # Impidimp
NPT.register_split_name(867, "Morg", "rem")   # Morgrem
NPT.register_split_name(868, "Grimm", "snarl")   # Grimmsnarl
NPT.register_split_name(869, "Obst", "agoon")   # Obstagoon
NPT.register_split_name(870, "Perrs", "erker")   # Perrserker
NPT.register_split_name(871, "Curs", "ola")   # Cursola
NPT.register_split_name(872, "Sirf", "etchd")   # Sirfetch’d
NPT.register_split_name(873, "MrR", "ime")   # Mr. Rime
NPT.register_split_name(874, "Rune", "rigus")   # Runerigus
NPT.register_split_name(875, "Milc", "ery")   # Milcery
NPT.register_split_name(876, "Alcr", "emie")   # Alcremie
NPT.register_split_name(877, "Fali", "nks")   # Falinks
NPT.register_split_name(878, "Pincu", "rchin")   # Pincurchin
NPT.register_split_name(879, "Sn", "om")   # Snom
NPT.register_split_name(880, "Fros", "moth")   # Frosmoth
NPT.register_split_name(881, "Stonj", "rner")   # Stonjourner
NPT.register_split_name(882, "Eis", "cue")   # Eiscue
NPT.register_split_name(883, "Inde", "edee")   # Indeedee
NPT.register_split_name(884, "Morp", "eko")   # Morpeko
NPT.register_split_name(885, "Cuf", "ant")   # Cufant
NPT.register_split_name(886, "Coppe", "rajah")   # Copperajah
NPT.register_split_name(887, "Drac", "ozolt")   # Dracozolt
NPT.register_split_name(888, "Arct", "ozolt")   # Arctozolt
NPT.register_split_name(889, "Drac", "ovish")   # Dracovish
NPT.register_split_name(890, "Arct", "ovish")   # Arctovish
NPT.register_split_name(891, "Dura", "ludon")   # Duraludon
NPT.register_split_name(892, "Dre", "epy")   # Dreepy
NPT.register_split_name(893, "Drak", "loak")   # Drakloak
NPT.register_split_name(894, "Drag", "apult")   # Dragapult
NPT.register_split_name(895, "Zac", "ian")   # Zacian
NPT.register_split_name(896, "Zama", "zenta")   # Zamazenta
NPT.register_split_name(897, "Eter", "natus")   # Eternatus
NPT.register_split_name(898, "Kub", "fu")   # Kubfu
NPT.register_split_name(899, "Ursh", "ifu")   # Urshifu
NPT.register_split_name(900, "Zar", "ude")   # Zarude
NPT.register_split_name(901, "Regi", "eleki")   # Regieleki
NPT.register_split_name(902, "Regi", "drago")   # Regidrago
NPT.register_split_name(903, "Glas", "trier")   # Glastrier
NPT.register_split_name(904, "Spec", "trier")   # Spectrier
NPT.register_split_name(905, "Caly", "rex")   # Calyrex
NPT.register_split_name(906, "Wyrd", "eer")   # Wyrdeer
NPT.register_split_name(907, "Klea", "vor")   # Kleavor
NPT.register_split_name(908, "Ursa", "luna")   # Ursaluna
NPT.register_split_name(909, "Bascu", "gion")   # Basculegion
NPT.register_split_name(910, "Snea", "sler")   # Sneasler
NPT.register_split_name(911, "Over", "qwil")   # Overqwil
NPT.register_split_name(912, "Enam", "orus")   # Enamorus
NPT.register_split_name(913, "Sprig", "atito")   # Sprigatito
NPT.register_split_name(914, "Flor", "agato")   # Floragato
NPT.register_split_name(915, "Meows", "rada")   # Meowscarada
NPT.register_split_name(916, "Fuec", "oco")   # Fuecoco
NPT.register_split_name(917, "Croc", "alor")   # Crocalor
NPT.register_split_name(918, "Skele", "dirge")   # Skeledirge
NPT.register_split_name(919, "Qua", "xly")   # Quaxly
NPT.register_split_name(920, "Quax", "well")   # Quaxwell
NPT.register_split_name(921, "Quaq", "uaval")   # Quaquaval
NPT.register_split_name(922, "Lech", "onk")   # Lechonk
NPT.register_split_name(923, "Oinko", "logne")   # Oinkologne
NPT.register_split_name(924, "Tarou", "ntula")   # Tarountula
NPT.register_split_name(925, "Spid", "ops")   # Spidops
NPT.register_split_name(926, "Nym", "ble")   # Nymble
NPT.register_split_name(927, "Lok", "ix")   # Lokix
NPT.register_split_name(928, "Paw", "mi")   # Pawmi
NPT.register_split_name(929, "Paw", "mo")   # Pawmo
NPT.register_split_name(930, "Paw", "mot")   # Pawmot
NPT.register_split_name(931, "Tand", "emaus")   # Tandemaus
NPT.register_split_name(932, "Maus", "hold")   # Maushold
NPT.register_split_name(933, "Fido", "ugh")   # Fidough
NPT.register_split_name(934, "Dach", "sbun")   # Dachsbun
NPT.register_split_name(935, "Smo", "liv")   # Smoliv
NPT.register_split_name(936, "Dol", "liv")   # Dolliv
NPT.register_split_name(937, "Arbo", "liva")   # Arboliva
NPT.register_split_name(938, "Squaw", "illy")   # Squawkabilly
NPT.register_split_name(939, "Nac", "li")   # Nacli
NPT.register_split_name(940, "Nacl", "stack")   # Naclstack
NPT.register_split_name(941, "Garg", "anacl")   # Garganacl
NPT.register_split_name(942, "Char", "cadet")   # Charcadet
NPT.register_split_name(943, "Arma", "rouge")   # Armarouge
NPT.register_split_name(944, "Ceru", "ledge")   # Ceruledge
NPT.register_split_name(945, "Tadb", "ulb")   # Tadbulb
NPT.register_split_name(946, "Bell", "ibolt")   # Bellibolt
NPT.register_split_name(947, "Watt", "rel")   # Wattrel
NPT.register_split_name(948, "Kilow", "trel")   # Kilowattrel
NPT.register_split_name(949, "Masc", "hiff")   # Maschiff
NPT.register_split_name(950, "Mabos", "stiff")   # Mabosstiff
NPT.register_split_name(951, "Shro", "odle")   # Shroodle
NPT.register_split_name(952, "Graf", "aiai")   # Grafaiai
NPT.register_split_name(953, "Bram", "blin")   # Bramblin
NPT.register_split_name(954, "Bramb", "hast")   # Brambleghast
NPT.register_split_name(955, "Toed", "scool")   # Toedscool
NPT.register_split_name(956, "Toeds", "cruel")   # Toedscruel
NPT.register_split_name(957, "Kla", "wf")   # Klawf
NPT.register_split_name(958, "Caps", "akid")   # Capsakid
NPT.register_split_name(959, "Scovi", "llain")   # Scovillain
NPT.register_split_name(960, "Rel", "lor")   # Rellor
NPT.register_split_name(961, "Rab", "sca")   # Rabsca
NPT.register_split_name(962, "Flit", "tle")   # Flittle
NPT.register_split_name(963, "Espa", "thra")   # Espathra
NPT.register_split_name(964, "Tink", "atink")   # Tinkatink
NPT.register_split_name(965, "Tink", "atuff")   # Tinkatuff
NPT.register_split_name(966, "Tink", "aton")   # Tinkaton
NPT.register_split_name(967, "Wigl", "ett")   # Wiglett
NPT.register_split_name(968, "Wugt", "rio")   # Wugtrio
NPT.register_split_name(969, "Bombi", "rdier")   # Bombirdier
NPT.register_split_name(970, "Fini", "zen")   # Finizen
NPT.register_split_name(971, "Pala", "fin")   # Palafin
NPT.register_split_name(972, "Var", "oom")   # Varoom
NPT.register_split_name(973, "Reva", "vroom")   # Revavroom
NPT.register_split_name(974, "Cycl", "izar")   # Cyclizar
NPT.register_split_name(975, "Orth", "worm")   # Orthworm
NPT.register_split_name(976, "Glim", "met")   # Glimmet
NPT.register_split_name(977, "Glim", "mora")   # Glimmora
NPT.register_split_name(978, "Grea", "vard")   # Greavard
NPT.register_split_name(979, "Hound", "stone")   # Houndstone
NPT.register_split_name(980, "Flam", "igo")   # Flamigo
NPT.register_split_name(981, "Ceto", "ddle")   # Cetoddle
NPT.register_split_name(982, "Ceti", "tan")   # Cetitan
NPT.register_split_name(983, "Vel", "uza")   # Veluza
NPT.register_split_name(984, "Dond", "ozo")   # Dondozo
NPT.register_split_name(985, "Tats", "ugiri")   # Tatsugiri
NPT.register_split_name(986, "Annih", "ilape")   # Annihilape
NPT.register_split_name(987, "Clod", "sire")   # Clodsire
NPT.register_split_name(988, "Fari", "giraf")   # Farigiraf
NPT.register_split_name(989, "Dudun", "arce")   # Dudunsparce
NPT.register_split_name(990, "King", "ambit")   # Kingambit
NPT.register_split_name(991, "Grea", "ttusk")   # Great Tusk
NPT.register_split_name(992, "Screa", "mtail")   # Scream Tail
NPT.register_split_name(993, "Brute", "nnet")   # Brute Bonnet
NPT.register_split_name(994, "Flutt", "mane")   # Flutter Mane
NPT.register_split_name(995, "Slith", "wing")   # Slither Wing
NPT.register_split_name(996, "Sandy", "ocks")   # Sandy Shocks
NPT.register_split_name(997, "IronT", "reads")   # Iron Treads
NPT.register_split_name(998, "IronB", "undle")   # Iron Bundle
NPT.register_split_name(999, "Iron", "hands")   # Iron Hands
NPT.register_split_name(1000, "IronJ", "ulis")   # Iron Jugulis
NPT.register_split_name(1001, "Iron", "moth")   # Iron Moth
NPT.register_split_name(1002, "IronT", "horns")   # Iron Thorns
NPT.register_split_name(1003, "Frig", "ibax")   # Frigibax
NPT.register_split_name(1004, "Arct", "ibax")   # Arctibax
NPT.register_split_name(1005, "Baxca", "libur")   # Baxcalibur
NPT.register_split_name(1006, "Gimmi", "ghoul")   # Gimmighoul
NPT.register_split_name(1007, "Ghol", "dengo")   # Gholdengo
NPT.register_split_name(1008, "WoCh", "ien")   # Wo-Chien
NPT.register_split_name(1009, "Chie", "npao")   # Chien-Pao
NPT.register_split_name(1010, "Tin", "glu")   # Ting-Lu
NPT.register_split_name(1011, "Chi", "yu")   # Chi-Yu
NPT.register_split_name(1012, "Roari", "moon")   # Roaring Moon
NPT.register_split_name(1013, "IronV", "iant")   # Iron Valiant
NPT.register_split_name(1014, "Kora", "idon")   # Koraidon
NPT.register_split_name(1015, "Mira", "idon")   # Miraidon
NPT.register_split_name(1016, "Walki", "wake")   # Walking Wake
NPT.register_split_name(1017, "IronL", "eaves")   # Iron Leaves
NPT.register_split_name(1018, "Dipp", "lin")   # Dipplin
NPT.register_split_name(1019, "Poltc", "eist")   # Poltchageist
NPT.register_split_name(1020, "Sini", "stcha")   # Sinistcha
NPT.register_split_name(1021, "Okid", "ogi")   # Okidogi
NPT.register_split_name(1022, "Munk", "idori")   # Munkidori
NPT.register_split_name(1023, "Fezan", "piti")   # Fezandipiti
NPT.register_split_name(1024, "Oger", "pon")   # Ogerpon
NPT.register_split_name(1025, "Archa", "ludon")   # Archaludon
NPT.register_split_name(1026, "Hydr", "apple")   # Hydrapple
NPT.register_split_name(1027, "Gougi", "fire")   # Gouging Fire
NPT.register_split_name(1028, "Ragin", "gbolt")   # Raging Bolt
NPT.register_split_name(1029, "IronB", "lder")   # Iron Boulder
NPT.register_split_name(1030, "Iron", "crown")   # Iron Crown
NPT.register_split_name(1031, "Tera", "pagos")   # Terapagos
NPT.register_split_name(1032, "Pech", "arunt")   # Pecharunt
