# 005_Abilities.rb
# Registers 189 abilities from PokéAPI that are missing from KIF.
# Auto-generated by generate_npt_moves_abilities.rb — do not edit by hand.
# Stubs: name + description registered, no effect handlers (do nothing in battle).
# IDs 7001-7189 reserved for NPT abilities.

if defined?(GameData) && defined?(GameData::Ability)
  class GameData::Ability
    class << self
      alias npt_abilities_original_load load
      def load
        npt_abilities_original_load

        # ── Aerilate ──
        unless GameData::Ability.exists?(:AERILATE)
          register({
            id:          :AERILATE,
            id_number:   7001,
            name:        "Aerilate",
            description: "Normal-type moves become Flying-type moves. The power of those moves is boosted a little."
          })
          MessageTypes.set(MessageTypes::Abilities,    7001, "Aerilate")
          MessageTypes.set(MessageTypes::AbilityDescs, 7001, "Normal-type moves become Flying-type moves. The power of those moves is boosted a little.")
        end

        # ── Anger Shell ──
        unless GameData::Ability.exists?(:ANGERSHELL)
          register({
            id:          :ANGERSHELL,
            id_number:   7002,
            name:        "Anger Shell",
            description: "Below half HP, it rages: defenses fall, offenses and speed rise."
          })
          MessageTypes.set(MessageTypes::Abilities,    7002, "Anger Shell")
          MessageTypes.set(MessageTypes::AbilityDescs, 7002, "When an attack causes its HP to drop to half or less, the Pokémon gets angry. This lowers its Defense and Sp. Def stats but boosts its Attack, Sp. Atk, and Speed stats.")
        end

        # ── Armor Tail ──
        unless GameData::Ability.exists?(:ARMORTAIL)
          register({
            id:          :ARMORTAIL,
            id_number:   7004,
            name:        "Armor Tail",
            description: "Tail shields head, blocking priority moves targeting it or allies."
          })
          MessageTypes.set(MessageTypes::Abilities,    7004, "Armor Tail")
          MessageTypes.set(MessageTypes::AbilityDescs, 7004, "The mysterious tail covering the Pokémon's head makes opponents unable to use priority moves against the Pokémon or its allies.")
        end

        # ── Aroma Veil ──
        unless GameData::Ability.exists?(:AROMAVEIL)
          register({
            id:          :AROMAVEIL,
            id_number:   7005,
            name:        "Aroma Veil",
            description: "Protects the Pokémon and its allies from effects that prevent the use of moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7005, "Aroma Veil")
          MessageTypes.set(MessageTypes::AbilityDescs, 7005, "Protects the Pokémon and its allies from effects that prevent the use of moves.")
        end

        # ── As One ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:ASONE)
          register({
            id:          :ASONE,
            id_number:   7006,
            name:        "As One",
            description: "This Ability combines the effects of both Calyrex's Unnerve Ability and Glastrier's Chilling Neigh Ability."
          })
          MessageTypes.set(MessageTypes::Abilities,    7006, "As One")
          MessageTypes.set(MessageTypes::AbilityDescs, 7006, "This Ability combines the effects of both Calyrex's Unnerve Ability and Glastrier's Chilling Neigh Ability.")
        end

        # ── As One ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:ASONE)
          register({
            id:          :ASONE,
            id_number:   7007,
            name:        "As One",
            description: "This Ability combines the effects of both Calyrex's Unnerve Ability and Spectrier's Grim Neigh Ability."
          })
          MessageTypes.set(MessageTypes::Abilities,    7007, "As One")
          MessageTypes.set(MessageTypes::AbilityDescs, 7007, "This Ability combines the effects of both Calyrex's Unnerve Ability and Spectrier's Grim Neigh Ability.")
        end

        # ── Aura Break ──
        unless GameData::Ability.exists?(:AURABREAK)
          register({
            id:          :AURABREAK,
            id_number:   7008,
            name:        "Aura Break",
            description: "The effects of “Aura” Abilities are reversed to lower the power of affected moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7008, "Aura Break")
          MessageTypes.set(MessageTypes::AbilityDescs, 7008, "The effects of “Aura” Abilities are reversed to lower the power of affected moves.")
        end

        # ── Ball Fetch ──
        unless GameData::Ability.exists?(:BALLFETCH)
          register({
            id:          :BALLFETCH,
            id_number:   7009,
            name:        "Ball Fetch",
            description: "If itemless, it retrieves the first failed Poké Ball throw.."
          })
          MessageTypes.set(MessageTypes::Abilities,    7009, "Ball Fetch")
          MessageTypes.set(MessageTypes::AbilityDescs, 7009, "If the Pokémon is not holding an item, it will fetch the Poké Ball from the first failed throw of the battle.")
        end

        # ── Battery ──
        unless GameData::Ability.exists?(:BATTERY)
          register({
            id:          :BATTERY,
            id_number:   7010,
            name:        "Battery",
            description: "Powers up ally Pokémon's special moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7010, "Battery")
          MessageTypes.set(MessageTypes::AbilityDescs, 7010, "Powers up ally Pokémon's special moves.")
        end

        # ── Battle Bond ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:BATTLEBOND)
          register({
            id:          :BATTLEBOND,
            id_number:   7011,
            name:        "Battle Bond",
            description: "When the Pokémon knocks out a target, its bond with its Trainer is strengthened, and its Attack, Sp. Atk, and Speed stats are boosted."
          })
          MessageTypes.set(MessageTypes::Abilities,    7011, "Battle Bond")
          MessageTypes.set(MessageTypes::AbilityDescs, 7011, "When the Pokémon knocks out a target, its bond with its Trainer is strengthened, and its Attack, Sp. Atk, and Speed stats are boosted.")
        end

        # ── Beads of Ruin ──
        unless GameData::Ability.exists?(:BEADSOFRUIN)
          register({
            id:          :BEADSOFRUIN,
            id_number:   7012,
            name:        "Beads of Ruin",
            description: "Ruinous beads lower all other Pokémon’s Special Defense."
          })
          MessageTypes.set(MessageTypes::Abilities,    7012, "Beads of Ruin")
          MessageTypes.set(MessageTypes::AbilityDescs, 7012, "The power of the Pokémon's ruinous beads lowers the Sp. Def stats of all Pokémon except itself.")
        end

        # ── Beast Boost ──
        unless GameData::Ability.exists?(:BEASTBOOST)
          register({
            id:          :BEASTBOOST,
            id_number:   7013,
            name:        "Beast Boost",
            description: "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon."
          })
          MessageTypes.set(MessageTypes::Abilities,    7013, "Beast Boost")
          MessageTypes.set(MessageTypes::AbilityDescs, 7013, "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.")
        end

        # ── Berserk ──
        unless GameData::Ability.exists?(:BERSERK)
          register({
            id:          :BERSERK,
            id_number:   7014,
            name:        "Berserk",
            description: "Below half HP after a hit, its Special Attack rises.."
          })
          MessageTypes.set(MessageTypes::Abilities,    7014, "Berserk")
          MessageTypes.set(MessageTypes::AbilityDescs, 7014, "Boosts the Pokémon's Sp. Atk stat when it takes a hit that causes its HP to drop to half or less.")
        end

        # ── Cheek Pouch ──
        unless GameData::Ability.exists?(:CHEEKPOUCH)
          register({
            id:          :CHEEKPOUCH,
            id_number:   7020,
            name:        "Cheek Pouch",
            description: "The Pokémon's HP is restored when it eats any Berry, in addition to the Berry's usual effect."
          })
          MessageTypes.set(MessageTypes::Abilities,    7020, "Cheek Pouch")
          MessageTypes.set(MessageTypes::AbilityDescs, 7020, "The Pokémon's HP is restored when it eats any Berry, in addition to the Berry's usual effect.")
        end

        # ── Chilling Neigh ──
        unless GameData::Ability.exists?(:CHILLINGNEIGH)
          register({
            id:          :CHILLINGNEIGH,
            id_number:   7021,
            name:        "Chilling Neigh",
            description: "When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat."
          })
          MessageTypes.set(MessageTypes::Abilities,    7021, "Chilling Neigh")
          MessageTypes.set(MessageTypes::AbilityDescs, 7021, "When the Pokémon knocks out a target, it utters a chilling neigh, which boosts its Attack stat.")
        end

        # ── Comatose ──
        unless GameData::Ability.exists?(:COMATOSE)
          register({
            id:          :COMATOSE,
            id_number:   7023,
            name:        "Comatose",
            description: "The Pokémon is always drowsing and will never wake up. It can attack while in its sleeping state."
          })
          MessageTypes.set(MessageTypes::Abilities,    7023, "Comatose")
          MessageTypes.set(MessageTypes::AbilityDescs, 7023, "The Pokémon is always drowsing and will never wake up. It can attack while in its sleeping state.")
        end

        # ── Commander ── MUST IMPLEMENT WATCH OUT FOR COOP TOO
        unless GameData::Ability.exists?(:COMMANDER)
          register({
            id:          :COMMANDER,
            id_number:   7024,
            name:        "Commander",
            description: "When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pokémon then issues commands from there."
          })
          MessageTypes.set(MessageTypes::Abilities,    7024, "Commander")
          MessageTypes.set(MessageTypes::AbilityDescs, 7024, "When the Pokémon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pokémon then issues commands from there.")
        end

        # ── Competitive ── ALREADY IN GAME
        unless GameData::Ability.exists?(:COMPETITIVE)
          register({
            id:          :COMPETITIVE,
            id_number:   7025,
            name:        "Competitive",
            description: "Boosts the Pokémon's Sp. Atk stat sharply when its stats are lowered by an opposing Pokémon."
          })
          MessageTypes.set(MessageTypes::Abilities,    7025, "Competitive")
          MessageTypes.set(MessageTypes::AbilityDescs, 7025, "Boosts the Pokémon's Sp. Atk stat sharply when its stats are lowered by an opposing Pokémon.")
        end

        # ── Corrosion ──
        unless GameData::Ability.exists?(:CORROSION)
          register({
            id:          :CORROSION,
            id_number:   7028,
            name:        "Corrosion",
            description: "The Pokémon can poison the target even if it's a Steel or Poison type."
          })
          MessageTypes.set(MessageTypes::Abilities,    7028, "Corrosion")
          MessageTypes.set(MessageTypes::AbilityDescs, 7028, "The Pokémon can poison the target even if it's a Steel or Poison type.")
        end

        # ── Costar ──
        unless GameData::Ability.exists?(:COSTAR)
          register({
            id:          :COSTAR,
            id_number:   7029,
            name:        "Costar",
            description: "When the Pokémon enters a battle, it copies an ally's stat changes."
          })
          MessageTypes.set(MessageTypes::Abilities,    7029, "Costar")
          MessageTypes.set(MessageTypes::AbilityDescs, 7029, "When the Pokémon enters a battle, it copies an ally's stat changes.")
        end

        # ── Cotton Down ──
        unless GameData::Ability.exists?(:COTTONDOWN)
          register({
            id:          :COTTONDOWN,
            id_number:   7030,
            name:        "Cotton Down",
            description: "When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stat of all Pokémon except itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7030, "Cotton Down")
          MessageTypes.set(MessageTypes::AbilityDescs, 7030, "When the Pokémon is hit by an attack, it scatters cotton fluff around and lowers the Speed stat of all Pokémon except itself.")
        end

        # ── Cud Chew ──
        unless GameData::Ability.exists?(:CUDCHEW)
          register({
            id:          :CUDCHEW,
            id_number:   7031,
            name:        "Cud Chew",
            description: "When the Pokémon eats a Berry, it will regurgitate that Berry at the end of the next turn and eat it one more time."
          })
          MessageTypes.set(MessageTypes::Abilities,    7031, "Cud Chew")
          MessageTypes.set(MessageTypes::AbilityDescs, 7031, "When the Pokémon eats a Berry, it will regurgitate that Berry at the end of the next turn and eat it one more time.")
        end

        # ── Curious Medicine ──
        unless GameData::Ability.exists?(:CURIOUSMEDICINE)
          register({
            id:          :CURIOUSMEDICINE,
            id_number:   7032,
            name:        "Curious Medicine",
            description: "When the Pokémon enters a battle, it scatters medicine from its shell, which removes all stat changes from allies."
          })
          MessageTypes.set(MessageTypes::Abilities,    7032, "Curious Medicine")
          MessageTypes.set(MessageTypes::AbilityDescs, 7032, "When the Pokémon enters a battle, it scatters medicine from its shell, which removes all stat changes from allies.")
        end

        # ── Dark Aura ──
        unless GameData::Ability.exists?(:DARKAURA)
          register({
            id:          :DARKAURA,
            id_number:   7033,
            name:        "Dark Aura",
            description: "Powers up each Pokémon’s Dark-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7033, "Dark Aura")
          MessageTypes.set(MessageTypes::AbilityDescs, 7033, "Powers up each Pokémon’s Dark-type moves.")
        end

        # ── Dauntless Shield ──
        unless GameData::Ability.exists?(:DAUNTLESSSHIELD)
          register({
            id:          :DAUNTLESSSHIELD,
            id_number:   7034,
            name:        "Dauntless Shield",
            description: "Boosts the Pokémon’s Defense stat the first time the Pokémon enters a battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7034, "Dauntless Shield")
          MessageTypes.set(MessageTypes::AbilityDescs, 7034, "Boosts the Pokémon’s Defense stat the first time the Pokémon enters a battle.")
        end

        # ── Defeatist ──
        unless GameData::Ability.exists?(:DEFEATIST)
          register({
            id:          :DEFEATIST,
            id_number:   7038,
            name:        "Defeatist",
            description: "Halves the Pokémon’s Attack and Sp. Atk stats when its HP becomes half or less."
          })
          MessageTypes.set(MessageTypes::Abilities,    7038, "Defeatist")
          MessageTypes.set(MessageTypes::AbilityDescs, 7038, "Halves the Pokémon’s Attack and Sp. Atk stats when its HP becomes half or less.")
        end

        # ── Delta Stream ──
        unless GameData::Ability.exists?(:DELTASTREAM)
          register({
            id:          :DELTASTREAM,
            id_number:   7039,
            name:        "Delta Stream",
            description: "The Pokémon changes the weather to eliminate all of the Flying type’s weaknesses."
          })
          MessageTypes.set(MessageTypes::Abilities,    7039, "Delta Stream")
          MessageTypes.set(MessageTypes::AbilityDescs, 7039, "The Pokémon changes the weather to eliminate all of the Flying type’s weaknesses.")
        end

        # ── Desolate Land ──
        unless GameData::Ability.exists?(:DESOLATELAND)
          register({
            id:          :DESOLATELAND,
            id_number:   7040,
            name:        "Desolate Land",
            description: "The Pokémon changes the weather to nullify Water-type attacks."
          })
          MessageTypes.set(MessageTypes::Abilities,    7040, "Desolate Land")
          MessageTypes.set(MessageTypes::AbilityDescs, 7040, "The Pokémon changes the weather to nullify Water-type attacks.")
        end

        # ── Dragon’s Maw ──
        unless GameData::Ability.exists?(:DRAGONSMAW)
          register({
            id:          :DRAGONSMAW,
            id_number:   7043,
            name:        "Dragon’s Maw",
            description: "Powers up Dragon-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7043, "Dragon’s Maw")
          MessageTypes.set(MessageTypes::AbilityDescs, 7043, "Powers up Dragon-type moves.")
        end

        # ── Earth Eater ──
        unless GameData::Ability.exists?(:EARTHEATER)
          register({
            id:          :EARTHEATER,
            id_number:   7044,
            name:        "Earth Eater",
            description: "If hit by a Ground-type move, the Pokémon has its HP restored instead of taking damage."
          })
          MessageTypes.set(MessageTypes::Abilities,    7044, "Earth Eater")
          MessageTypes.set(MessageTypes::AbilityDescs, 7044, "If hit by a Ground-type move, the Pokémon has its HP restored instead of taking damage.")
        end

        # ── Electric Surge ──
        unless GameData::Ability.exists?(:ELECTRICSURGE)
          register({
            id:          :ELECTRICSURGE,
            id_number:   7045,
            name:        "Electric Surge",
            description: "Turns the ground into Electric Terrain when the Pokémon enters a battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7045, "Electric Surge")
          MessageTypes.set(MessageTypes::AbilityDescs, 7045, "Turns the ground into Electric Terrain when the Pokémon enters a battle.")
        end

        # ── Electromorphosis ──
        unless GameData::Ability.exists?(:ELECTROMORPHOSIS)
          register({
            id:          :ELECTROMORPHOSIS,
            id_number:   7046,
            name:        "Electromorphosis",
            description: "The Pokémon becomes charged when it takes damage, boosting the power of the next Electric-type move the Pokémon uses."
          })
          MessageTypes.set(MessageTypes::Abilities,    7046, "Electromorphosis")
          MessageTypes.set(MessageTypes::AbilityDescs, 7046, "The Pokémon becomes charged when it takes damage, boosting the power of the next Electric-type move the Pokémon uses.")
        end

        # ── Embody Aspect ──
        unless GameData::Ability.exists?(:EMBODYASPECT)
          register({
            id:          :EMBODYASPECT,
            id_number:   7047,
            name:        "Embody Aspect",
            description: "The Pokémon's heart fills with memories, causing the Mask to shine and one of the Pokémon's stats to be boosted."
          })
          MessageTypes.set(MessageTypes::Abilities,    7047, "Embody Aspect")
          MessageTypes.set(MessageTypes::AbilityDescs, 7047, "The Pokémon's heart fills with memories, causing the Mask to shine and one of the Pokémon's stats to be boosted.")
        end

        # ── Fairy Aura ──
        unless GameData::Ability.exists?(:FAIRYAURA)
          register({
            id:          :FAIRYAURA,
            id_number:   7049,
            name:        "Fairy Aura",
            description: "Powers up each Pokémon’s Fairy-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7049, "Fairy Aura")
          MessageTypes.set(MessageTypes::AbilityDescs, 7049, "Powers up each Pokémon’s Fairy-type moves.")
        end

        # ── Flower Gift ──
        unless GameData::Ability.exists?(:FLOWERGIFT)
          register({
            id:          :FLOWERGIFT,
            id_number:   7051,
            name:        "Flower Gift",
            description: "Boosts the Attack and Sp. Def stats of itself and allies in harsh sunlight."
          })
          MessageTypes.set(MessageTypes::Abilities,    7051, "Flower Gift")
          MessageTypes.set(MessageTypes::AbilityDescs, 7051, "Boosts the Attack and Sp. Def stats of itself and allies in harsh sunlight.")
        end

        # ── Flower Veil ──
        unless GameData::Ability.exists?(:FLOWERVEIL)
          register({
            id:          :FLOWERVEIL,
            id_number:   7052,
            name:        "Flower Veil",
            description: "Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats."
          })
          MessageTypes.set(MessageTypes::Abilities,    7052, "Flower Veil")
          MessageTypes.set(MessageTypes::AbilityDescs, 7052, "Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats.")
        end

        # ── Forecast ──
        unless GameData::Ability.exists?(:FORECAST)
          register({
            id:          :FORECAST,
            id_number:   7053,
            name:        "Forecast",
            description: "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice."
          })
          MessageTypes.set(MessageTypes::Abilities,    7053, "Forecast")
          MessageTypes.set(MessageTypes::AbilityDescs, 7053, "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.")
        end

        # ── Full Metal Body ──
        unless GameData::Ability.exists?(:FULLMETALBODY)
          register({
            id:          :FULLMETALBODY,
            id_number:   7057,
            name:        "Full Metal Body",
            description: "Prevents other Pokémon’s moves or Abilities from lowering the Pokémon’s stats."
          })
          MessageTypes.set(MessageTypes::Abilities,    7057, "Full Metal Body")
          MessageTypes.set(MessageTypes::AbilityDescs, 7057, "Prevents other Pokémon’s moves or Abilities from lowering the Pokémon’s stats.")
        end

        # ── Fur Coat ──
        unless GameData::Ability.exists?(:FURCOAT)
          register({
            id:          :FURCOAT,
            id_number:   7058,
            name:        "Fur Coat",
            description: "Halves the damage from physical moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7058, "Fur Coat")
          MessageTypes.set(MessageTypes::AbilityDescs, 7058, "Halves the damage from physical moves.")
        end

        # ── Galvanize ──
        unless GameData::Ability.exists?(:GALVANIZE)
          register({
            id:          :GALVANIZE,
            id_number:   7059,
            name:        "Galvanize",
            description: "Normal-type moves become Electric-type moves. The power of those moves is boosted a little."
          })
          MessageTypes.set(MessageTypes::Abilities,    7059, "Galvanize")
          MessageTypes.set(MessageTypes::AbilityDescs, 7059, "Normal-type moves become Electric-type moves. The power of those moves is boosted a little.")
        end

        # ── Good as Gold ──
        unless GameData::Ability.exists?(:GOODASGOLD)
          register({
            id:          :GOODASGOLD,
            id_number:   7060,
            name:        "Good as Gold",
            description: "A body of pure, solid gold gives the Pokémon full immunity to other Pokémon's status moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7060, "Good as Gold")
          MessageTypes.set(MessageTypes::AbilityDescs, 7060, "A body of pure, solid gold gives the Pokémon full immunity to other Pokémon's status moves.")
        end

        # ── Gorilla Tactics ──
        unless GameData::Ability.exists?(:GORILLATACTICS)
          register({
            id:          :GORILLATACTICS,
            id_number:   7061,
            name:        "Gorilla Tactics",
            description: "Boosts the Pokémon’s Attack stat but only allows the use of the first selected move."
          })
          MessageTypes.set(MessageTypes::Abilities,    7061, "Gorilla Tactics")
          MessageTypes.set(MessageTypes::AbilityDescs, 7061, "Boosts the Pokémon’s Attack stat but only allows the use of the first selected move.")
        end

        # ── Grass Pelt ──
        unless GameData::Ability.exists?(:GRASSPELT)
          register({
            id:          :GRASSPELT,
            id_number:   7063,
            name:        "Grass Pelt",
            description: "Boosts the Pokémon's Defense stat on Grassy Terrain."
          })
          MessageTypes.set(MessageTypes::Abilities,    7063, "Grass Pelt")
          MessageTypes.set(MessageTypes::AbilityDescs, 7063, "Boosts the Pokémon's Defense stat on Grassy Terrain.")
        end

        # ── Grassy Surge ──
        unless GameData::Ability.exists?(:GRASSYSURGE)
          register({
            id:          :GRASSYSURGE,
            id_number:   7064,
            name:        "Grassy Surge",
            description: "Turns the ground into Grassy Terrain when the Pokémon enters a battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7064, "Grassy Surge")
          MessageTypes.set(MessageTypes::AbilityDescs, 7064, "Turns the ground into Grassy Terrain when the Pokémon enters a battle.")
        end

        # ── Grim Neigh ──
        unless GameData::Ability.exists?(:GRIMNEIGH)
          register({
            id:          :GRIMNEIGH,
            id_number:   7065,
            name:        "Grim Neigh",
            description: "When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat."
          })
          MessageTypes.set(MessageTypes::Abilities,    7065, "Grim Neigh")
          MessageTypes.set(MessageTypes::AbilityDescs, 7065, "When the Pokémon knocks out a target, it utters a terrifying neigh, which boosts its Sp. Atk stat.")
        end

        # ── Guard Dog ──
        unless GameData::Ability.exists?(:GUARDDOG)
          register({
            id:          :GUARDDOG,
            id_number:   7066,
            name:        "Guard Dog",
            description: "Boosts the Pokémon’s Attack stat if intimidated. Moves and items that would force the Pokémon to switch out also fail to work."
          })
          MessageTypes.set(MessageTypes::Abilities,    7066, "Guard Dog")
          MessageTypes.set(MessageTypes::AbilityDescs, 7066, "Boosts the Pokémon’s Attack stat if intimidated. Moves and items that would force the Pokémon to switch out also fail to work.")
        end

        # ── Gulp Missile ──
        unless GameData::Ability.exists?(:GULPMISSILE)
          register({
            id:          :GULPMISSILE,
            id_number:   7068,
            name:        "Gulp Missile",
            description: "When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack."
          })
          MessageTypes.set(MessageTypes::Abilities,    7068, "Gulp Missile")
          MessageTypes.set(MessageTypes::AbilityDescs, 7068, "When the Pokémon uses Surf or Dive, it will come back with prey. When it takes damage, it will spit out the prey to attack.")
        end

        # ── Hadron Engine ──
        unless GameData::Ability.exists?(:HADRONENGINE)
          register({
            id:          :HADRONENGINE,
            id_number:   7069,
            name:        "Hadron Engine",
            description: "Turns the ground into Electric Terrain when the Pokémon enters a battle. The futuristic engine within the Pokémon also boosts its Sp. Atk stat on Electric Terrain."
          })
          MessageTypes.set(MessageTypes::Abilities,    7069, "Hadron Engine")
          MessageTypes.set(MessageTypes::AbilityDescs, 7069, "Turns the ground into Electric Terrain when the Pokémon enters a battle. The futuristic engine within the Pokémon also boosts its Sp. Atk stat on Electric Terrain.")
        end

        # ── Heatproof ──
        unless GameData::Ability.exists?(:HEATPROOF)
          register({
            id:          :HEATPROOF,
            id_number:   7070,
            name:        "Heatproof",
            description: "The Pokémon's heatproof body halves the damage taken from Fire-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7070, "Heatproof")
          MessageTypes.set(MessageTypes::AbilityDescs, 7070, "The Pokémon's heatproof body halves the damage taken from Fire-type moves.")
        end

        # ── Hospitality ──
        unless GameData::Ability.exists?(:HOSPITALITY)
          register({
            id:          :HOSPITALITY,
            id_number:   7074,
            name:        "Hospitality",
            description: "When the Pokémon enters a battle, it showers its ally with hospitality, restoring a small amount of the ally's HP"
          })
          MessageTypes.set(MessageTypes::Abilities,    7074, "Hospitality")
          MessageTypes.set(MessageTypes::AbilityDescs, 7074, "When the Pokémon enters a battle, it showers its ally with hospitality, restoring a small amount of the ally's HP")
        end

        # ── Hunger Switch ──
        unless GameData::Ability.exists?(:HUNGERSWITCH)
          register({
            id:          :HUNGERSWITCH,
            id_number:   7076,
            name:        "Hunger Switch",
            description: "The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of every turn."
          })
          MessageTypes.set(MessageTypes::Abilities,    7076, "Hunger Switch")
          MessageTypes.set(MessageTypes::AbilityDescs, 7076, "The Pokémon changes its form, alternating between its Full Belly Mode and Hangry Mode after the end of every turn.")
        end

        # ── Ice Face ──
        unless GameData::Ability.exists?(:ICEFACE)
          register({
            id:          :ICEFACE,
            id_number:   7077,
            name:        "Ice Face",
            description: "The Pokémon's ice head can take a physical attack as a substitute, but the attack also changes the Pokémon's appearance. The ice will be restored when it snows."
          })
          MessageTypes.set(MessageTypes::Abilities,    7077, "Ice Face")
          MessageTypes.set(MessageTypes::AbilityDescs, 7077, "The Pokémon's ice head can take a physical attack as a substitute, but the attack also changes the Pokémon's appearance. The ice will be restored when it snows.")
        end

        # ── Ice Scales ──
        unless GameData::Ability.exists?(:ICESCALES)
          register({
            id:          :ICESCALES,
            id_number:   7078,
            name:        "Ice Scales",
            description: "The Pokémon is protected by ice scales, which halve the damage taken from special moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7078, "Ice Scales")
          MessageTypes.set(MessageTypes::AbilityDescs, 7078, "The Pokémon is protected by ice scales, which halve the damage taken from special moves.")
        end

        # ── Intrepid Sword ──
        unless GameData::Ability.exists?(:INTREPIDSWORD)
          register({
            id:          :INTREPIDSWORD,
            id_number:   7081,
            name:        "Intrepid Sword",
            description: "Boosts the Pokémon’s Attack stat the first time the Pokémon enters a battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7081, "Intrepid Sword")
          MessageTypes.set(MessageTypes::AbilityDescs, 7081, "Boosts the Pokémon’s Attack stat the first time the Pokémon enters a battle.")
        end

        # ── Libero ──
        unless GameData::Ability.exists?(:LIBERO)
          register({
            id:          :LIBERO,
            id_number:   7084,
            name:        "Libero",
            description: "Changes the Pokémon's type to the type of the move it's about to use. This works only once each time the Pokémon enters battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7084, "Libero")
          MessageTypes.set(MessageTypes::AbilityDescs, 7084, "Changes the Pokémon's type to the type of the move it's about to use. This works only once each time the Pokémon enters battle.")
        end

        # ── Lingering Aroma ──
        unless GameData::Ability.exists?(:LINGERINGAROMA)
          register({
            id:          :LINGERINGAROMA,
            id_number:   7086,
            name:        "Lingering Aroma",
            description: "Contact with the Pokémon changes the attacker's Ability to Lingering Aroma."
          })
          MessageTypes.set(MessageTypes::Abilities,    7086, "Lingering Aroma")
          MessageTypes.set(MessageTypes::AbilityDescs, 7086, "Contact with the Pokémon changes the attacker's Ability to Lingering Aroma.")
        end

        # ── Liquid Voice ──
        unless GameData::Ability.exists?(:LIQUIDVOICE)
          register({
            id:          :LIQUIDVOICE,
            id_number:   7087,
            name:        "Liquid Voice",
            description: "Sound-based moves become Water-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7087, "Liquid Voice")
          MessageTypes.set(MessageTypes::AbilityDescs, 7087, "Sound-based moves become Water-type moves.")
        end

        # ── Long Reach ──
        unless GameData::Ability.exists?(:LONGREACH)
          register({
            id:          :LONGREACH,
            id_number:   7088,
            name:        "Long Reach",
            description: "The Pokémon uses its moves without making contact with the target."
          })
          MessageTypes.set(MessageTypes::Abilities,    7088, "Long Reach")
          MessageTypes.set(MessageTypes::AbilityDescs, 7088, "The Pokémon uses its moves without making contact with the target.")
        end

        # ── Mega Launcher ──
        unless GameData::Ability.exists?(:MEGALAUNCHER)
          register({
            id:          :MEGALAUNCHER,
            id_number:   7092,
            name:        "Mega Launcher",
            description: "Powers up pulse moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7092, "Mega Launcher")
          MessageTypes.set(MessageTypes::AbilityDescs, 7092, "Powers up pulse moves.")
        end

        # ── Mimicry ──
        unless GameData::Ability.exists?(:MIMICRY)
          register({
            id:          :MIMICRY,
            id_number:   7094,
            name:        "Mimicry",
            description: "Changes the Pokémon’s type depending on the terrain."
          })
          MessageTypes.set(MessageTypes::Abilities,    7094, "Mimicry")
          MessageTypes.set(MessageTypes::AbilityDescs, 7094, "Changes the Pokémon’s type depending on the terrain.")
        end

        # ── Mind’s Eye ──
        unless GameData::Ability.exists?(:MINDSEYE)
          register({
            id:          :MINDSEYE,
            id_number:   7095,
            name:        "Mind’s Eye",
            description: "The Pokémon ignores changes to opponents' evasiveness, its accuracy can't be lowered, and it can hit Ghost types with Normal-type and Fighting-type moves"
          })
          MessageTypes.set(MessageTypes::Abilities,    7095, "Mind’s Eye")
          MessageTypes.set(MessageTypes::AbilityDescs, 7095, "The Pokémon ignores changes to opponents' evasiveness, its accuracy can't be lowered, and it can hit Ghost types with Normal-type and Fighting-type moves")
        end

        # ── Mirror Armor ──
        unless GameData::Ability.exists?(:MIRRORARMOR)
          register({
            id:          :MIRRORARMOR,
            id_number:   7096,
            name:        "Mirror Armor",
            description: "Bounces back only the stat-lowering effects that the Pokémon receives."
          })
          MessageTypes.set(MessageTypes::Abilities,    7096, "Mirror Armor")
          MessageTypes.set(MessageTypes::AbilityDescs, 7096, "Bounces back only the stat-lowering effects that the Pokémon receives.")
        end

        # ── Misty Surge ──
        unless GameData::Ability.exists?(:MISTYSURGE)
          register({
            id:          :MISTYSURGE,
            id_number:   7097,
            name:        "Misty Surge",
            description: "Turns the ground into Misty Terrain when the Pokémon enters a battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7097, "Misty Surge")
          MessageTypes.set(MessageTypes::AbilityDescs, 7097, "Turns the ground into Misty Terrain when the Pokémon enters a battle.")
        end

        # ── Mycelium Might ──
        unless GameData::Ability.exists?(:MYCELIUMMIGHT)
          register({
            id:          :MYCELIUMMIGHT,
            id_number:   7100,
            name:        "Mycelium Might",
            description: "The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target."
          })
          MessageTypes.set(MessageTypes::Abilities,    7100, "Mycelium Might")
          MessageTypes.set(MessageTypes::AbilityDescs, 7100, "The Pokémon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target.")
        end

        # ── Neutralizing Gas ──
        unless GameData::Ability.exists?(:NEUTRALIZINGGAS)
          register({
            id:          :NEUTRALIZINGGAS,
            id_number:   7101,
            name:        "Neutralizing Gas",
            description: "While the Pokémon is in the battle, the effects of all other Pokémon's Abilities will be nullified or will not be triggered."
          })
          MessageTypes.set(MessageTypes::Abilities,    7101, "Neutralizing Gas")
          MessageTypes.set(MessageTypes::AbilityDescs, 7101, "While the Pokémon is in the battle, the effects of all other Pokémon's Abilities will be nullified or will not be triggered.")
        end

        # ── Normalize ──
        unless GameData::Ability.exists?(:NORMALIZE)
          register({
            id:          :NORMALIZE,
            id_number:   7103,
            name:        "Normalize",
            description: "All the Pokémon’s moves become Normal type. The power of those moves is boosted a little."
          })
          MessageTypes.set(MessageTypes::Abilities,    7103, "Normalize")
          MessageTypes.set(MessageTypes::AbilityDescs, 7103, "All the Pokémon’s moves become Normal type. The power of those moves is boosted a little.")
        end

        # ── Opportunist ──
        unless GameData::Ability.exists?(:OPPORTUNIST)
          register({
            id:          :OPPORTUNIST,
            id_number:   7106,
            name:        "Opportunist",
            description: "If an opponent's stat is boosted, the Pokémon seizes the opportunity to boost the same stat for itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7106, "Opportunist")
          MessageTypes.set(MessageTypes::AbilityDescs, 7106, "If an opponent's stat is boosted, the Pokémon seizes the opportunity to boost the same stat for itself.")
        end

        # ── Orichalcum Pulse ──
        unless GameData::Ability.exists?(:ORICHALCUMPULSE)
          register({
            id:          :ORICHALCUMPULSE,
            id_number:   7107,
            name:        "Orichalcum Pulse",
            description: "Turns the sunlight harsh when the Pokémon enters a battle. The ancient pulse thrumming through the Pokémon also boosts its Attack stat in harsh sunlight."
          })
          MessageTypes.set(MessageTypes::Abilities,    7107, "Orichalcum Pulse")
          MessageTypes.set(MessageTypes::AbilityDescs, 7107, "Turns the sunlight harsh when the Pokémon enters a battle. The ancient pulse thrumming through the Pokémon also boosts its Attack stat in harsh sunlight.")
        end

        # ── Parental Bond ──
        unless GameData::Ability.exists?(:PARENTALBOND)
          register({
            id:          :PARENTALBOND,
            id_number:   7108,
            name:        "Parental Bond",
            description: "Parent and child each attacks."
          })
          MessageTypes.set(MessageTypes::Abilities,    7108, "Parental Bond")
          MessageTypes.set(MessageTypes::AbilityDescs, 7108, "Parent and child each attacks.")
        end

        # ── Pastel Veil ──
        unless GameData::Ability.exists?(:PASTELVEIL)
          register({
            id:          :PASTELVEIL,
            id_number:   7110,
            name:        "Pastel Veil",
            description: "Protects the Pokémon and its ally Pokémon from being poisoned."
          })
          MessageTypes.set(MessageTypes::Abilities,    7110, "Pastel Veil")
          MessageTypes.set(MessageTypes::AbilityDescs, 7110, "Protects the Pokémon and its ally Pokémon from being poisoned.")
        end

        # ── Perish Body ──
        unless GameData::Ability.exists?(:PERISHBODY)
          register({
            id:          :PERISHBODY,
            id_number:   7112,
            name:        "Perish Body",
            description: "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7112, "Perish Body")
          MessageTypes.set(MessageTypes::AbilityDescs, 7112, "When hit by a move that makes direct contact, the Pokémon and the attacker will faint after three turns unless they switch out of battle.")
        end

        # ── Poison Puppeteer ──
        unless GameData::Ability.exists?(:POISONPUPPETEER)
          register({
            id:          :POISONPUPPETEER,
            id_number:   7113,
            name:        "Poison Puppeteer",
            description: "Pokémon poisoned by Pecharunt's moves will also become confused."
          })
          MessageTypes.set(MessageTypes::Abilities,    7113, "Poison Puppeteer")
          MessageTypes.set(MessageTypes::AbilityDescs, 7113, "Pokémon poisoned by Pecharunt's moves will also become confused.")
        end

        # ── Power Construct ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:POWERCONSTRUCT)
          register({
            id:          :POWERCONSTRUCT,
            id_number:   7114,
            name:        "Power Construct",
            description: "Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Forme."
          })
          MessageTypes.set(MessageTypes::Abilities,    7114, "Power Construct")
          MessageTypes.set(MessageTypes::AbilityDescs, 7114, "Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Forme.")
        end

        # ── Power of Alchemy ──
        unless GameData::Ability.exists?(:POWEROFALCHEMY)
          register({
            id:          :POWEROFALCHEMY,
            id_number:   7116,
            name:        "Power of Alchemy",
            description: "The Pokémon copies the Ability of a defeated ally."
          })
          MessageTypes.set(MessageTypes::Abilities,    7116, "Power of Alchemy")
          MessageTypes.set(MessageTypes::AbilityDescs, 7116, "The Pokémon copies the Ability of a defeated ally.")
        end

        # ── Power Spot ──
        unless GameData::Ability.exists?(:POWERSPOT)
          register({
            id:          :POWERSPOT,
            id_number:   7117,
            name:        "Power Spot",
            description: "Just being next to the Pokémon powers up moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7117, "Power Spot")
          MessageTypes.set(MessageTypes::AbilityDescs, 7117, "Just being next to the Pokémon powers up moves.")
        end

        # ── Primordial Sea ──
        unless GameData::Ability.exists?(:PRIMORDIALSEA)
          register({
            id:          :PRIMORDIALSEA,
            id_number:   7119,
            name:        "Primordial Sea",
            description: "The Pokémon changes the weather to nullify Fire-type attacks."
          })
          MessageTypes.set(MessageTypes::Abilities,    7119, "Primordial Sea")
          MessageTypes.set(MessageTypes::AbilityDescs, 7119, "The Pokémon changes the weather to nullify Fire-type attacks.")
        end

        # ── Propeller Tail ──
        unless GameData::Ability.exists?(:PROPELLERTAIL)
          register({
            id:          :PROPELLERTAIL,
            id_number:   7120,
            name:        "Propeller Tail",
            description: "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7120, "Propeller Tail")
          MessageTypes.set(MessageTypes::AbilityDescs, 7120, "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.")
        end

        # ── Protosynthesis ──
        unless GameData::Ability.exists?(:PROTOSYNTHESIS)
          register({
            id:          :PROTOSYNTHESIS,
            id_number:   7121,
            name:        "Protosynthesis",
            description: "Boosts the Pokémon's most proficient stat in harsh sunlight or if the Pokémon is holding Booster Energy."
          })
          MessageTypes.set(MessageTypes::Abilities,    7121, "Protosynthesis")
          MessageTypes.set(MessageTypes::AbilityDescs, 7121, "Boosts the Pokémon's most proficient stat in harsh sunlight or if the Pokémon is holding Booster Energy.")
        end

        # ── Psychic Surge ──
        unless GameData::Ability.exists?(:PSYCHICSURGE)
          register({
            id:          :PSYCHICSURGE,
            id_number:   7122,
            name:        "Psychic Surge",
            description: "Turns the ground into Psychic Terrain when the Pokémon enters a battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7122, "Psychic Surge")
          MessageTypes.set(MessageTypes::AbilityDescs, 7122, "Turns the ground into Psychic Terrain when the Pokémon enters a battle.")
        end

        # ── Punk Rock ──
        unless GameData::Ability.exists?(:PUNKROCK)
          register({
            id:          :PUNKROCK,
            id_number:   7123,
            name:        "Punk Rock",
            description: "Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7123, "Punk Rock")
          MessageTypes.set(MessageTypes::AbilityDescs, 7123, "Boosts the power of sound-based moves. The Pokémon also takes half the damage from these kinds of moves.")
        end

        # ── Pure Power ──
        unless GameData::Ability.exists?(:PUREPOWER)
          register({
            id:          :PUREPOWER,
            id_number:   7124,
            name:        "Pure Power",
            description: "Using its pure power, the Pokémon doubles its Attack stat."
          })
          MessageTypes.set(MessageTypes::Abilities,    7124, "Pure Power")
          MessageTypes.set(MessageTypes::AbilityDescs, 7124, "Using its pure power, the Pokémon doubles its Attack stat.")
        end

        # ── Purifying Salt ──
        unless GameData::Ability.exists?(:PURIFYINGSALT)
          register({
            id:          :PURIFYINGSALT,
            id_number:   7125,
            name:        "Purifying Salt",
            description: "The Pokémon's pure salt protects it from status conditions and halves the damage taken from Ghost-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7125, "Purifying Salt")
          MessageTypes.set(MessageTypes::AbilityDescs, 7125, "The Pokémon's pure salt protects it from status conditions and halves the damage taken from Ghost-type moves.")
        end

        # ── Quark Drive ──
        unless GameData::Ability.exists?(:QUARKDRIVE)
          register({
            id:          :QUARKDRIVE,
            id_number:   7126,
            name:        "Quark Drive",
            description: "Boosts the Pokémon's most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy."
          })
          MessageTypes.set(MessageTypes::Abilities,    7126, "Quark Drive")
          MessageTypes.set(MessageTypes::AbilityDescs, 7126, "Boosts the Pokémon's most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy.")
        end

        # ── Queenly Majesty ──
        unless GameData::Ability.exists?(:QUEENLYMAJESTY)
          register({
            id:          :QUEENLYMAJESTY,
            id_number:   7127,
            name:        "Queenly Majesty",
            description: "Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7127, "Queenly Majesty")
          MessageTypes.set(MessageTypes::AbilityDescs, 7127, "Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves.")
        end

        # ── Quick Draw ──
        unless GameData::Ability.exists?(:QUICKDRAW)
          register({
            id:          :QUICKDRAW,
            id_number:   7128,
            name:        "Quick Draw",
            description: "Enables the Pokémon to move first occasionally."
          })
          MessageTypes.set(MessageTypes::Abilities,    7128, "Quick Draw")
          MessageTypes.set(MessageTypes::AbilityDescs, 7128, "Enables the Pokémon to move first occasionally.")
        end

        # ── Receiver ──
        unless GameData::Ability.exists?(:RECEIVER)
          register({
            id:          :RECEIVER,
            id_number:   7129,
            name:        "Receiver",
            description: "The Pokémon copies the Ability of a defeated ally."
          })
          MessageTypes.set(MessageTypes::Abilities,    7129, "Receiver")
          MessageTypes.set(MessageTypes::AbilityDescs, 7129, "The Pokémon copies the Ability of a defeated ally.")
        end

        # ── Ripen ──
        unless GameData::Ability.exists?(:RIPEN)
          register({
            id:          :RIPEN,
            id_number:   7130,
            name:        "Ripen",
            description: "Ripens Berries and doubles their effect."
          })
          MessageTypes.set(MessageTypes::Abilities,    7130, "Ripen")
          MessageTypes.set(MessageTypes::AbilityDescs, 7130, "Ripens Berries and doubles their effect.")
        end

        # ── RKS System ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:RKSSYSTEM)
          register({
            id:          :RKSSYSTEM,
            id_number:   7131,
            name:        "RKS System",
            description: "Changes the Pokémon’s type to match the memory disc it holds."
          })
          MessageTypes.set(MessageTypes::Abilities,    7131, "RKS System")
          MessageTypes.set(MessageTypes::AbilityDescs, 7131, "Changes the Pokémon’s type to match the memory disc it holds.")
        end

        # ── Rocky Payload ──
        unless GameData::Ability.exists?(:ROCKYPAYLOAD)
          register({
            id:          :ROCKYPAYLOAD,
            id_number:   7132,
            name:        "Rocky Payload",
            description: "Powers up Rock-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7132, "Rocky Payload")
          MessageTypes.set(MessageTypes::AbilityDescs, 7132, "Powers up Rock-type moves.")
        end

        # ── Sand Spit ──
        unless GameData::Ability.exists?(:SANDSPIT)
          register({
            id:          :SANDSPIT,
            id_number:   7134,
            name:        "Sand Spit",
            description: "The Pokémon creates a sandstorm when it's hit by an attack."
          })
          MessageTypes.set(MessageTypes::Abilities,    7134, "Sand Spit")
          MessageTypes.set(MessageTypes::AbilityDescs, 7134, "The Pokémon creates a sandstorm when it's hit by an attack.")
        end

        # ── Schooling ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:SCHOOLING)
          register({
            id:          :SCHOOLING,
            id_number:   7136,
            name:        "Schooling",
            description: "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low."
          })
          MessageTypes.set(MessageTypes::Abilities,    7136, "Schooling")
          MessageTypes.set(MessageTypes::AbilityDescs, 7136, "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.")
        end

        # ── Screen Cleaner ──
        unless GameData::Ability.exists?(:SCREENCLEANER)
          register({
            id:          :SCREENCLEANER,
            id_number:   7137,
            name:        "Screen Cleaner",
            description: "When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon."
          })
          MessageTypes.set(MessageTypes::Abilities,    7137, "Screen Cleaner")
          MessageTypes.set(MessageTypes::AbilityDescs, 7137, "When the Pokémon enters a battle, the effects of Light Screen, Reflect, and Aurora Veil are nullified for both opposing and ally Pokémon.")
        end

        # ── Seed Sower ──
        unless GameData::Ability.exists?(:SEEDSOWER)
          register({
            id:          :SEEDSOWER,
            id_number:   7138,
            name:        "Seed Sower",
            description: "Turns the ground into Grassy Terrain when the Pokémon is hit by an attack."
          })
          MessageTypes.set(MessageTypes::Abilities,    7138, "Seed Sower")
          MessageTypes.set(MessageTypes::AbilityDescs, 7138, "Turns the ground into Grassy Terrain when the Pokémon is hit by an attack.")
        end

        # ── Shadow Shield ──
        unless GameData::Ability.exists?(:SHADOWSHIELD)
          register({
            id:          :SHADOWSHIELD,
            id_number:   7142,
            name:        "Shadow Shield",
            description: "Reduces the amount of damage the Pokémon takes while its HP is full."
          })
          MessageTypes.set(MessageTypes::Abilities,    7142, "Shadow Shield")
          MessageTypes.set(MessageTypes::AbilityDescs, 7142, "Reduces the amount of damage the Pokémon takes while its HP is full.")
        end

        # ── Sharpness ──
        unless GameData::Ability.exists?(:SHARPNESS)
          register({
            id:          :SHARPNESS,
            id_number:   7144,
            name:        "Sharpness",
            description: "Powers up slicing moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7144, "Sharpness")
          MessageTypes.set(MessageTypes::AbilityDescs, 7144, "Powers up slicing moves.")
        end

        # ── Slush Rush ──
        unless GameData::Ability.exists?(:SLUSHRUSH)
          register({
            id:          :SLUSHRUSH,
            id_number:   7147,
            name:        "Slush Rush",
            description: "Boosts the Pokémon's Speed stat in snow."
          })
          MessageTypes.set(MessageTypes::Abilities,    7147, "Slush Rush")
          MessageTypes.set(MessageTypes::AbilityDescs, 7147, "Boosts the Pokémon's Speed stat in snow.")
        end

        # ── Soul-Heart ──
        unless GameData::Ability.exists?(:SOULHEART)
          register({
            id:          :SOULHEART,
            id_number:   7148,
            name:        "Soul-Heart",
            description: "Boosts the Pokémon's Sp. Atk stat every time another Pokémon faints."
          })
          MessageTypes.set(MessageTypes::Abilities,    7148, "Soul-Heart")
          MessageTypes.set(MessageTypes::AbilityDescs, 7148, "Boosts the Pokémon's Sp. Atk stat every time another Pokémon faints.")
        end

        # ── Stakeout ──
        unless GameData::Ability.exists?(:STAKEOUT)
          register({
            id:          :STAKEOUT,
            id_number:   7152,
            name:        "Stakeout",
            description: "Doubles the damage dealt to a target that has just switched into battle."
          })
          MessageTypes.set(MessageTypes::Abilities,    7152, "Stakeout")
          MessageTypes.set(MessageTypes::AbilityDescs, 7152, "Doubles the damage dealt to a target that has just switched into battle.")
        end

        # ── Stalwart ──
        unless GameData::Ability.exists?(:STALWART)
          register({
            id:          :STALWART,
            id_number:   7153,
            name:        "Stalwart",
            description: "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7153, "Stalwart")
          MessageTypes.set(MessageTypes::AbilityDescs, 7153, "Ignores the effects of opposing Pokémon's Abilities and moves that draw in moves.")
        end

        # ── Stamina ──
        unless GameData::Ability.exists?(:STAMINA)
          register({
            id:          :STAMINA,
            id_number:   7154,
            name:        "Stamina",
            description: "Boosts the Defense stat when the Pokémon is hit by an attack."
          })
          MessageTypes.set(MessageTypes::Abilities,    7154, "Stamina")
          MessageTypes.set(MessageTypes::AbilityDescs, 7154, "Boosts the Defense stat when the Pokémon is hit by an attack.")
        end

        # ── Steam Engine ──
        unless GameData::Ability.exists?(:STEAMENGINE)
          register({
            id:          :STEAMENGINE,
            id_number:   7156,
            name:        "Steam Engine",
            description: "Boosts the Speed stat drastically when the Pokémon is hit by a Fire- or Water-type move."
          })
          MessageTypes.set(MessageTypes::Abilities,    7156, "Steam Engine")
          MessageTypes.set(MessageTypes::AbilityDescs, 7156, "Boosts the Speed stat drastically when the Pokémon is hit by a Fire- or Water-type move.")
        end

        # ── Steely Spirit ──
        unless GameData::Ability.exists?(:STEELYSPIRIT)
          register({
            id:          :STEELYSPIRIT,
            id_number:   7157,
            name:        "Steely Spirit",
            description: "Powers up the Steel-type moves of the Pokémon and its allies."
          })
          MessageTypes.set(MessageTypes::Abilities,    7157, "Steely Spirit")
          MessageTypes.set(MessageTypes::AbilityDescs, 7157, "Powers up the Steel-type moves of the Pokémon and its allies.")
        end

        # ── Supersweet Syrup ──
        unless GameData::Ability.exists?(:SUPERSWEETSYRUP)
          register({
            id:          :SUPERSWEETSYRUP,
            id_number:   7158,
            name:        "Supersweet Syrup",
            description: "Lowers the evasion of opposing Pokémon by 1 stage when first sent into battle"
          })
          MessageTypes.set(MessageTypes::Abilities,    7158, "Supersweet Syrup")
          MessageTypes.set(MessageTypes::AbilityDescs, 7158, "Lowers the evasion of opposing Pokémon by 1 stage when first sent into battle")
        end

        # ── Supreme Overlord ──
        unless GameData::Ability.exists?(:SUPREMEOVERLORD)
          register({
            id:          :SUPREMEOVERLORD,
            id_number:   7159,
            name:        "Supreme Overlord",
            description: "When the Pokémon enters a battle, its Attack and Sp. Atk stats are slightly boosted for each of the allies in its party that have already been defeated."
          })
          MessageTypes.set(MessageTypes::Abilities,    7159, "Supreme Overlord")
          MessageTypes.set(MessageTypes::AbilityDescs, 7159, "When the Pokémon enters a battle, its Attack and Sp. Atk stats are slightly boosted for each of the allies in its party that have already been defeated.")
        end

        # ── Surge Surfer ──
        unless GameData::Ability.exists?(:SURGESURFER)
          register({
            id:          :SURGESURFER,
            id_number:   7160,
            name:        "Surge Surfer",
            description: "Doubles the Pokémon's Speed stat on Electric Terrain."
          })
          MessageTypes.set(MessageTypes::Abilities,    7160, "Surge Surfer")
          MessageTypes.set(MessageTypes::AbilityDescs, 7160, "Doubles the Pokémon's Speed stat on Electric Terrain.")
        end

        # ── Sword of Ruin ──
        unless GameData::Ability.exists?(:SWORDOFRUIN)
          register({
            id:          :SWORDOFRUIN,
            id_number:   7161,
            name:        "Sword of Ruin",
            description: "The power of the Pokémon's ruinous sword lowers the Defense stats of all Pokémon except itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7161, "Sword of Ruin")
          MessageTypes.set(MessageTypes::AbilityDescs, 7161, "The power of the Pokémon's ruinous sword lowers the Defense stats of all Pokémon except itself.")
        end

        # ── Symbiosis ──
        unless GameData::Ability.exists?(:SYMBIOSIS)
          register({
            id:          :SYMBIOSIS,
            id_number:   7162,
            name:        "Symbiosis",
            description: "The Pokémon passes its held item to an ally that has used up an item."
          })
          MessageTypes.set(MessageTypes::Abilities,    7162, "Symbiosis")
          MessageTypes.set(MessageTypes::AbilityDescs, 7162, "The Pokémon passes its held item to an ally that has used up an item.")
        end

        # ── Tablets of Ruin ──
        unless GameData::Ability.exists?(:TABLETSOFRUIN)
          register({
            id:          :TABLETSOFRUIN,
            id_number:   7163,
            name:        "Tablets of Ruin",
            description: "The power of the Pokémon's ruinous wooden tablets lowers the Attack stats of all Pokémon except itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7163, "Tablets of Ruin")
          MessageTypes.set(MessageTypes::AbilityDescs, 7163, "The power of the Pokémon's ruinous wooden tablets lowers the Attack stats of all Pokémon except itself.")
        end

        # ── Tangling Hair ──
        unless GameData::Ability.exists?(:TANGLINGHAIR)
          register({
            id:          :TANGLINGHAIR,
            id_number:   7164,
            name:        "Tangling Hair",
            description: "Contact with the Pokémon lowers the attacker's Speed stat."
          })
          MessageTypes.set(MessageTypes::Abilities,    7164, "Tangling Hair")
          MessageTypes.set(MessageTypes::AbilityDescs, 7164, "Contact with the Pokémon lowers the attacker's Speed stat.")
        end

        # ── Tera Shell ──
        unless GameData::Ability.exists?(:TERASHELL)
          register({
            id:          :TERASHELL,
            id_number:   7166,
            name:        "Tera Shell",
            description: "The Pokémon's shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective."
          })
          MessageTypes.set(MessageTypes::Abilities,    7166, "Tera Shell")
          MessageTypes.set(MessageTypes::AbilityDescs, 7166, "The Pokémon's shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.")
        end

        # ── Tera Shift ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:TERASHIFT)
          register({
            id:          :TERASHIFT,
            id_number:   7167,
            name:        "Tera Shift",
            description: "When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form."
          })
          MessageTypes.set(MessageTypes::Abilities,    7167, "Tera Shift")
          MessageTypes.set(MessageTypes::AbilityDescs, 7167, "When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.")
        end

        # ── Teraform Zero ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:TERAFORMZERO)
          register({
            id:          :TERAFORMZERO,
            id_number:   7168,
            name:        "Teraform Zero",
            description: "When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero."
          })
          MessageTypes.set(MessageTypes::Abilities,    7168, "Teraform Zero")
          MessageTypes.set(MessageTypes::AbilityDescs, 7168, "When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.")
        end

        # ── Thermal Exchange ──
        unless GameData::Ability.exists?(:THERMALEXCHANGE)
          register({
            id:          :THERMALEXCHANGE,
            id_number:   7169,
            name:        "Thermal Exchange",
            description: "Boosts the Attack stat when the Pokémon is hit by a Fire-type move. The Pokémon also cannot be burned."
          })
          MessageTypes.set(MessageTypes::Abilities,    7169, "Thermal Exchange")
          MessageTypes.set(MessageTypes::AbilityDescs, 7169, "Boosts the Attack stat when the Pokémon is hit by a Fire-type move. The Pokémon also cannot be burned.")
        end

        # ── Tough Claws ──
        unless GameData::Ability.exists?(:TOUGHCLAWS)
          register({
            id:          :TOUGHCLAWS,
            id_number:   7171,
            name:        "Tough Claws",
            description: "Powers up moves that make direct contact."
          })
          MessageTypes.set(MessageTypes::Abilities,    7171, "Tough Claws")
          MessageTypes.set(MessageTypes::AbilityDescs, 7171, "Powers up moves that make direct contact.")
        end

        # ── Toxic Boost ──
        unless GameData::Ability.exists?(:TOXICBOOST)
          register({
            id:          :TOXICBOOST,
            id_number:   7172,
            name:        "Toxic Boost",
            description: "Powers up physical moves when the Pokémon is poisoned."
          })
          MessageTypes.set(MessageTypes::Abilities,    7172, "Toxic Boost")
          MessageTypes.set(MessageTypes::AbilityDescs, 7172, "Powers up physical moves when the Pokémon is poisoned.")
        end

        # ── Toxic Chain ──
        unless GameData::Ability.exists?(:TOXICCHAIN)
          register({
            id:          :TOXICCHAIN,
            id_number:   7173,
            name:        "Toxic Chain",
            description: "The power of the Pokémon's toxic chain may badly poison any target the Pokémon hits with a move"
          })
          MessageTypes.set(MessageTypes::Abilities,    7173, "Toxic Chain")
          MessageTypes.set(MessageTypes::AbilityDescs, 7173, "The power of the Pokémon's toxic chain may badly poison any target the Pokémon hits with a move")
        end

        # ── Toxic Debris ──
        unless GameData::Ability.exists?(:TOXICDEBRIS)
          register({
            id:          :TOXICDEBRIS,
            id_number:   7174,
            name:        "Toxic Debris",
            description: "Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7174, "Toxic Debris")
          MessageTypes.set(MessageTypes::AbilityDescs, 7174, "Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves.")
        end

        # ── Transistor ──
        unless GameData::Ability.exists?(:TRANSISTOR)
          register({
            id:          :TRANSISTOR,
            id_number:   7175,
            name:        "Transistor",
            description: "Powers up Electric-type moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7175, "Transistor")
          MessageTypes.set(MessageTypes::AbilityDescs, 7175, "Powers up Electric-type moves.")
        end

        # ── Triage ──
        unless GameData::Ability.exists?(:TRIAGE)
          register({
            id:          :TRIAGE,
            id_number:   7176,
            name:        "Triage",
            description: "Gives priority to the Pokémon's healing moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7176, "Triage")
          MessageTypes.set(MessageTypes::AbilityDescs, 7176, "Gives priority to the Pokémon's healing moves.")
        end

        # ── Unseen Fist ──
        unless GameData::Ability.exists?(:UNSEENFIST)
          register({
            id:          :UNSEENFIST,
            id_number:   7177,
            name:        "Unseen Fist",
            description: "If the Pokémon uses moves that make direct contact, it can attack the target even if the target protects itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7177, "Unseen Fist")
          MessageTypes.set(MessageTypes::AbilityDescs, 7177, "If the Pokémon uses moves that make direct contact, it can attack the target even if the target protects itself.")
        end

        # ── Vessel of Ruin ──
        unless GameData::Ability.exists?(:VESSELOFRUIN)
          register({
            id:          :VESSELOFRUIN,
            id_number:   7179,
            name:        "Vessel of Ruin",
            description: "The power of the Pokémon's ruinous vessel lowers the Sp. Atk stats of all Pokémon except itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7179, "Vessel of Ruin")
          MessageTypes.set(MessageTypes::AbilityDescs, 7179, "The power of the Pokémon's ruinous vessel lowers the Sp. Atk stats of all Pokémon except itself.")
        end

        # ── Victory Star ──
        unless GameData::Ability.exists?(:VICTORYSTAR)
          register({
            id:          :VICTORYSTAR,
            id_number:   7180,
            name:        "Victory Star",
            description: "Boosts the accuracy of its allies and itself."
          })
          MessageTypes.set(MessageTypes::Abilities,    7180, "Victory Star")
          MessageTypes.set(MessageTypes::AbilityDescs, 7180, "Boosts the accuracy of its allies and itself.")
        end

        # ── Wandering Spirit ──
        unless GameData::Ability.exists?(:WANDERINGSPIRIT)
          register({
            id:          :WANDERINGSPIRIT,
            id_number:   7181,
            name:        "Wandering Spirit",
            description: "The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact."
          })
          MessageTypes.set(MessageTypes::Abilities,    7181, "Wandering Spirit")
          MessageTypes.set(MessageTypes::AbilityDescs, 7181, "The Pokémon exchanges Abilities with a Pokémon that hits it with a move that makes direct contact.")
        end

        # ── Water Bubble ──
        unless GameData::Ability.exists?(:WATERBUBBLE)
          register({
            id:          :WATERBUBBLE,
            id_number:   7183,
            name:        "Water Bubble",
            description: "Lowers the power of Fire-type moves that hit the Pokémon and prevents it from being burned."
          })
          MessageTypes.set(MessageTypes::Abilities,    7183, "Water Bubble")
          MessageTypes.set(MessageTypes::AbilityDescs, 7183, "Lowers the power of Fire-type moves that hit the Pokémon and prevents it from being burned.")
        end

        # ── Well-Baked Body ──
        unless GameData::Ability.exists?(:WELLBAKEDBODY)
          register({
            id:          :WELLBAKEDBODY,
            id_number:   7185,
            name:        "Well-Baked Body",
            description: "The Pokémon takes no damage when hit by Fire-type moves. Instead, its Defense stat is sharply boosted."
          })
          MessageTypes.set(MessageTypes::Abilities,    7185, "Well-Baked Body")
          MessageTypes.set(MessageTypes::AbilityDescs, 7185, "The Pokémon takes no damage when hit by Fire-type moves. Instead, its Defense stat is sharply boosted.")
        end

        # ── Wind Power ──
        unless GameData::Ability.exists?(:WINDPOWER)
          register({
            id:          :WINDPOWER,
            id_number:   7186,
            name:        "Wind Power",
            description: "The Pokémon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses."
          })
          MessageTypes.set(MessageTypes::Abilities,    7186, "Wind Power")
          MessageTypes.set(MessageTypes::AbilityDescs, 7186, "The Pokémon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pokémon uses.")
        end

        # ── Wind Rider ──
        unless GameData::Ability.exists?(:WINDRIDER)
          register({
            id:          :WINDRIDER,
            id_number:   7187,
            name:        "Wind Rider",
            description: "Boosts the Pokémon's Attack stat if Tailwind takes effect or if the Pokémon is hit by a wind move. The Pokémon also takes no damage from wind moves."
          })
          MessageTypes.set(MessageTypes::Abilities,    7187, "Wind Rider")
          MessageTypes.set(MessageTypes::AbilityDescs, 7187, "Boosts the Pokémon's Attack stat if Tailwind takes effect or if the Pokémon is hit by a wind move. The Pokémon also takes no damage from wind moves.")
        end

        # ── Zen Mode ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:ZENMODE)
          register({
            id:          :ZENMODE,
            id_number:   7188,
            name:        "Zen Mode",
            description: "Changes the Pokémon’s shape when HP is half or less."
          })
          MessageTypes.set(MessageTypes::Abilities,    7188, "Zen Mode")
          MessageTypes.set(MessageTypes::AbilityDescs, 7188, "Changes the Pokémon’s shape when HP is half or less.")
        end

        # ── Zero to Hero ── MUST IMPLEMENT
        unless GameData::Ability.exists?(:ZEROTOHERO)
          register({
            id:          :ZEROTOHERO,
            id_number:   7189,
            name:        "Zero to Hero",
            description: "The Pokémon transforms into its Hero Form when it switches out."
          })
          MessageTypes.set(MessageTypes::Abilities,    7189, "Zero to Hero")
          MessageTypes.set(MessageTypes::AbilityDescs, 7189, "The Pokémon transforms into its Hero Form when it switches out.")
        end

      end  # load
    end  # class << self
  end  # GameData::Ability
end
